CMakeLists.txt

Adds an export target so that you can `find_package(SwiftWin32)`.

Add exports

---

Sources/Support/Rect+UIExtensions.swift
Sources/UI/View.swift

- computed property RECT getter
- RECT setter as asignment operator
- using Rect extentions call AdjustWindowRect to set window size so that panel is the size of rect excluding the border size.

Add Rect extension functions and window panel size adjustments.

---

CMakeLists.txt
Sources/Support/Logging.swift
Sources/UI/Font.swift

Switch from the `print` to logging via `swift-log`.  This provides a
much more structured approach to handling errors in the UI framework.

Switch to swift-log for logging

---

CMakeLists.txt
Sources/Support/WindowsHandle.swift
Sources/UI/Font.swift
Sources/UI/Label.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift

Create a new `ManagedHandle` type that represents a managed handle.  The
handle is explicitly marked as owning or referencing.  An owning handle
will be deallocated at the end of the lifetime of the object.  The
constructor explicitly indicates whether the type is owned or not.
This management allows for proper handle type specific handling of the
handles that are being trafficked across the C/Swift boundary.

UI: generalize the windows handle management

---

Examples/HelloSwift.exe.manifest

Extend the manifest to support DPI awareness.  This is preferable to API
driver control, however, both are needed.

Examples: improve manifest for DPI awareness

---

Sources/Support/WindowsHandle.swift
Sources/UI/Font.swift

Force the `HandleValue` conformance and change the generic parameter
for `ManagedHandle` to the `HandleValue`.  This allows multiple managed
handles by avoiding the overlapping conformances for
`UnmanagedMutablePointer`.

Handle: permit multiple managed handle types

---

Sources/CG/Rect.swift

Add `Rect(origin:size:)` and `Rect(x:y:width:height:)` with `Int`
convenience constructor.

CG: add additional `Rect` constructors

---

CMakeLists.txt
Sources/Application/ApplicationMain.swift
Sources/UI/Screen.swift
Sources/UI/View.swift

This adds the `Screen` and sets up per-monitor awareness.  Address long
standing TODO items and scale the UI as per the DPI on the monitor.
This finally gets the window handling correct enough to remove the odd
checks that had been inserted originally.

UI: add `Screen` type and use it for DPI awareness

---

Examples/HelloSwift.swift
Sources/Application/Application.swift
Sources/Application/ApplicationDelegate.swift
Sources/Application/ApplicationMain.swift

Hook the application window procedure to intercept the `WM_ACTIVATEAPP`
window message.  Use this to identify the state of the application.
Extended `ApplicationDelegate` to permit the application to handle
the event.

Application: add some form of application lifecycle notifications

---

Examples/CMakeLists.txt
Sources/CMakeLists.txt

Rely on autolinking for the GDI32 linkage.  This was improved in the
Swift 5.3 timeframe, so provide a compatibility shim for 5.2.

build: remove Gdi32 linkage

---

Examples/CMakeLists.txt
Examples/HelloSwift.swift
Sources/Application/Application.swift
Sources/Application/ApplicationDelegate.swift
Sources/Application/ApplicationMain.swift

Make the `ApplicationMain(_:_:_:_:)` signature match the original
desired state.  Applications can now mark the `ApplicationDelegate` as
`@main` have the entry point be synthesized.

Application: add support for `@main` based entry

---

CMakeLists.txt
Sources/CMakeLists.txt
Sources/CWinRT/CMakeLists.txt
Sources/CWinRT/WinRTAugmentation.cc
Sources/CWinRT/XAMLSupport.c
Sources/CWinRT/include/CWinRT.h
Sources/CWinRT/include/CWinRTMacros.h
Sources/CWinRT/include/module.modulemap
azure-pipelines.yml

The Windows Runtime interfaces are largely C++.  Add some C wrappers
for Windows Runtime interfaces to allow the construction of WPF based
UI elements for embedding in the Swift application.

WinRT: sketch out C shims for Windows Runtime

---

Sources/Support/WinSDK+Extensions.swift

These keys are now part of the WinSDK module as vended by the Swift
project.  Don't bother with local definitions when building with a new
enough toolchain.

Support: guard the definitions appropriately

---

CMakeLists.txt
Sources/Application/ApplicationMain.swift
Sources/CMakeLists.txt
Sources/Support/Logging.swift
Sources/UI/Device.swift
Sources/UI/Font.swift
Sources/UI/TraitCollection.swift
Sources/UI/View.swift

Fallback to `OutputDebugStringW` when swift-log is unavailable.  Rename
the `ENABLE_LOGGING` option to `WITH_SWIFT_LOG` as it is intended now to
build with support for swift-log.  This allows us to provide logging
even if `swift-log` is unavailable.

Support: use `OutputDebugStringW` if swift-log is unavailable

---

Sources/Application/ApplicationMain.swift

This renames the Window Procedure hook to accommodate additional
hooking.

Application: rename `hHook` (NFC)

---

Sources/UI/View.swift

Rather than save off the DPI, query it when necessary.  This ensures
that changes to the DPI are reflected.

UI: do not cache the DPI for the View

---

Sources/Application/ApplicationMain.swift

Ensure that we guard the type instantiation for `Application`.  Properly
unwrap the `delegate` parameter which may be `nil` as per the signature
and guard the type instantiation for `delegate` as well.

Application: validate type instantiation

---

Sources/UI/View.swift

This finally adds support for adjusting the `frame` for the View.  Doing
so will scale the new value for the current DPI and update the position
of the view within the parent view.

UI: make `frame` settable

---

Sources/UI/TextField.swift

The font was not being stored as the property was a computed property.
Add an explicit backing store to ensure that we do not loose the font.

UI: add a font backing store for TextField

---

Sources/UI/TextField.swift

Use the RichEdit control for the simple input as well.  This will allow
better control of text alignment.

UI: convert TextField to use RichEdit

---

Sources/UI/TextField.swift

`TextField` should allow setting the text alignment.  However, `EDIT`
controls cannot dynamically change the text alignment.  Now that
`TextField` is backed by a Rich Edit control, we can switch the
alignment freely.

UI: add `TextAlignment` enumeration for `TextField`

---

Examples/Calculator.swift

Use the `textAlignment` property on `TextField` now that it properly
functions.  This allows us to remove some of the details that the API is
attempting to abstract for us.

Calculator: remove window style usage (NFC)

---

Sources/UI/Button.swift
Sources/UI/Label.swift
Sources/UI/ProgressView.swift
Sources/UI/Slider.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift
Sources/UI/View.swift
Sources/UI/Window.swift
Sources/UI/WindowClass.swift

Remove the `class` and `style parameters to present a more complete
veneer over the Win32/GDI interfaces.  This moves us closer towards
removing the exposure to Win32 from the user's perspective.

UI: remove `class:style:` from `init`

---

Sources/UI/Window.swift

Thanks to @farzonl for pointing out that the class styles were not being
applied to the Window class.  They were incorrectly being applied as
Window styles rather than class styles.

UI: handle class styles properly

---

Sources/Support/WinSDK+Extensions.swift
Sources/UI/View.swift
Sources/UI/WindowClass.swift

Use a String for the class name rather than an array.  Swap the
condition for the overlapped window frame check as overlapped is
comparatively less likely.  Force unwrap the pointer from
`CreateWindowExW` which returns a nullable pointer.

UI: redo class definition for rich edit

---

Sources/UI/Window.swift

`WM_QUIT` is never posted to the Window message loop.  It is only
accessible in the application message loop.  Remove the extraneous
message.

UI: remove `WM_QUIT` from `Window`

---

Sources/UI/Screen.swift
Sources/UI/Window.swift

This adds the monitor handle to the screen to allow mapping the screen
to the monitor.
Add the helper `==` operators for comparing a screen to a `HMONITOR`.
These are internal as the user should not need to be aware of the
Windows types.
Add the screen property to the Window type.  This allows querying the
screen from the Window.

UI: enable mapping the window to the screen

---

Sources/Application/ApplicationMain.swift

@jbatez pointed out that `GetMessageW` can return a value which is
non-boolean for errors.  Explicitly cast the function to convert the
boolean parameter to a `CInt`.

Application: un-BOOL `GetMessageW`

---

Sources/Application/ApplicationMain.swift
Sources/Support/WinSDK+Extensions.swift

Provide overloads to allow the extraction of the integral value from the
`BOOL` return type.

Application: extract `GetMessageW` overloads

---

Sources/Support/WinSDK+Extensions.swift

This enables `EnableMenuItem` overloads to enable accessing the return
value as `CInt` to handle errors.

WinSDK: add `EnableMenuItem` overloads

---

Examples/Calculator.swift
Examples/HelloSwift.swift
Sources/UI/Window.swift

There is no need to expose the `OnDestroy` event to the user.  This is
handled properly by default.  The only need is to post the quit message
(`WM_QUIT`) when the window is destroyed to terminate the app.

UI: remove `OnDestroy` from `WindowDelegate`

---

Sources/UI/Window.swift

This does not get triggered when the window is created.  This is not
useful to expose to clients, simply remove it.

UI: remove `WM_CREATE` callback

---

Sources/CMakeLists.txt
Sources/UI/Screen.swift
Sources/UI/TraitEnvironment.swift
Sources/UI/Window.swift

Intercept the `WM_DPICHANGED` message in the window hook procedure.
That notification is then broadcasted to the Screen enumeration which
represents the display (i.e. trigger a refresh on all monitors).
In theory, we should be able to identify the intended recipient, and use
the HWND to map the monitor, refreshing just that monitor.  This would
make the processing significantly cheaper.
The intent here is to identify the screen, then broadcast the DPI change
notification to all the windows on that screen to trigger a re-layout of
the window, properly handling the scaling change.

UI: start wiring up `WM_DPICHANGED` notifications

---

Sources/UI/Font.swift

Add constructors for retrieving the system default monospaced fonts.  As
Windows does not have the concept of a system default font (unlike Linux
where FontConfig will provide the ability to set the default font for
the font family), we emulate that by specifying NULL for the family
name, which allows the system to provide the first font that matches the
remaining constraints.

UI: add support to construct monospaced fonts

---

Examples/Calculator.swift
Examples/HelloSwift.swift
Sources/Application/Application.swift
Sources/UI/Window.swift

Add new `Window` APIs to enable tracking of Window instances in the
application.  This starts laying the framework to support modelling
applications with multiple scenes.

Application: track application Windows

---

Sources/UI/Label.swift
Sources/UI/TextView.swift

We would immediately drop the Font which would free the font.  This
resulted in the font setting never taking effect.  This is the same
issue as the `TextField`.  Replicate the fix to `Label` and `TextView`.

UI: add backing store for Font

---

Examples/HelloSwift.swift
Sources/CMakeLists.txt
Sources/Support/PropertyWrappers.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift

The window text property is very useful as it is used in a number of
places.  It is backed by an opaque storage that is handled by the
implementation.  Querying requires determining the size and then
allocating a buffer and retrieving a copy.
The `_Win32WindowText` property wrapper allows exposing the window
property itself through an alternate name.  This requires some extra
setup to pass along the view that the property wrapper is associated
with to allow setting up the `HWND`.  However, this allows for a single
implementation to be shared across all the various sites.

Support: introduce WindowText property wrapper

---

Sources/UI/Button.swift
Sources/UI/DatePicker.swift
Sources/UI/Label.swift
Sources/UI/ProgressView.swift
Sources/UI/Slider.swift
Sources/UI/Switch.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift
Sources/UI/Window.swift

These fields are meant to record the window class for the view and the
window style properties.  They are only used for construction and only
need to be accessed by the constructor.  Make them only accessible by
the type itself.

UI: make `class` and `style` private

---

Sources/UI/Color.swift

Split up the implementation of `Color` into more logical groups.  Add a
grayscale constructor and define additional fixed colors.
Add a set of adaptive colors which use the system contrast and theme to
define the color.

UI: flesh out `Color` further

---

Sources/UI/Window.swift

The `WM_PAINT` event is not needed for clients, remove the event from
both the `WindowDelegate` protocol and the dispatch handling in the
subclass procedure.

UI: remove `WM_PAINT` event from the `WindowDelegate`

---

Sources/UI/Font.swift

The `Font` type constructs itself through owning `HFONT`.  Add a simple
helper constructor for that to ease the construction of `Font` from
`CreateFontW`.

UI: simplify `Font` constructor (NFC)

---

Sources/Support/Logging.swift

This covers the full levels that `swift-log` provides allowing for use
of additional logging levels even without `swift-log`.

Support: add additional logging levels

---

Sources/Support/PropertyWrappers.swift
Sources/UI/Label.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift

The window font property is very useful as it is used in a number of
places.  The font requires storage to persist the font handle while the
font remains in use.  However, the property itself is queried from the
window to ensure that the default values can be retrieved.

Support: introduce Win32Font property wrapper

---

Examples/Calculator/Calculator.swift
Examples/UICatalog/UICatalog.swift
Sources/UI/Button.swift

This helper was meant for the UICatalog and Calculator example programs.
Make them local to the examples.

UI: remove helper constructor for `Button`

---

Sources/UI/Button.swift
Sources/UI/DatePicker.swift
Sources/UI/Switch.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift

Many of the older controls provided a default value for the
`init(frame:)` constructor.  Homogenise them to require the
parameter.

UI: remove default value parameter for `init`

---

Examples/Calculator/Calculator.swift
Examples/UICatalog/UICatalog.swift
Sources/CMakeLists.txt
Sources/UI/ViewController.swift
Sources/UI/Window.swift

Introduce the new `ViewController` type that represents the controller
for a MVC pattern for the application.  This now allows us to remove the
extension for the window title as the title is now a property on the
associated controller for the window.

UI: introduce `ViewController`

---

Examples/UICatalog/UICatalog.swift
Sources/Support/Rect+UIExtensions.swift

This is not exactly usable as the height and width should be specified.
The other pattern that can be done is to create full-screen windows
using `Screen.default.bounds`.

Support: remove `Rect.default`

---

Examples/UICatalog/UICatalog.swift
Sources/Application/ApplicationMain.swift

Send the `applicationWillTerminate` notification to the application
delegate before tearing down the process.

Application: wire up `applicationWillTerminate(_)`

---

Examples/UICatalog/UICatalog.swift
Sources/UI/Button.swift
Sources/UI/Control.swift

Add basic handling for event action triggering to `Control`.  This
allows for a better modelling of events which leaks fewer details about
the internals of the GDI/Win32 implementation.

UI: model action/target model for Control events

---

.gitignore
Package.swift

Using this package as a means to test the progress on
swift-package-manager port on Windows.  This allows building Swift/Win32
with swift-package-manager.

build: add an initial Package.swift

---

Sources/Support/WinSDK+Extensions.swift
Sources/UI/Device.swift

Add functionality to track the device orientation.  At the moment, this
does not provide the notifications as no notifications are currently
implemented.  However, this enables querying the instantaneous
orientation of the device.

UI: add support to track the device orientation

---

Sources/Support/PropertyWrappers.swift
Sources/UI/Label.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift
Sources/UI/View.swift

Make the `font` property a property of `View` rather than each control
implementing it.  Controls which expose control over the font can then
override the property and forward the `View` property which is limited
to `internal` access.
Furthermore simplify the property by making it a normal stored property
with a `didSet` observer.  This will become more useful as a subsequent
change will initialise the property always to ensure that the defaulted
font is the system font.

UI: sink `font` property to `View`

---

Sources/UI/Color.swift

Add definitions for standard colors for elements such as the window
background and primary text and placeholder text.  This will enable a
more structured way to set colors for the rendering.

UI: define some standard colors for UI elements

---

Examples/UICatalog/UICatalog.swift
Sources/UI/Stepper.swift
Sources/UI/View.swift

This creates the Stepper MessengerProxy to dispatch the notifications to
the control.  Add this into the `UICatalog` demo program as well.

UI: wire up `.valueChanged` actions for `Stepper`

---

Sources/UI/Button.swift
Sources/UI/DatePicker.swift
Sources/UI/Stepper.swift
Sources/UI/Switch.swift
Sources/UI/TextView.swift
Sources/UI/Window.swift

These functions are referenced only from the subclass itself, it does
not need to be exposed to other sources.

UI: make subclass procedures `private`

---

Sources/UI/Color.swift

As there are different colour spaces and constructors in use here,
represent the colour as a discriminated union of the values which can be
tagged.  The value is converted when required.  This will allow us to
add in a HSV (HSB) representation.

UI: alter the representation of `Color`

---

Sources/UI/Color.swift

Rather than inlining the math for the constructor of `COLORREF`, which
was slightly incorrect, use an extension to allow the conversion to be
centralised and then use that to construct the `COLORREF`.

UI: centralise the `COLORREF` constructor

---

Sources/UI/Button.swift

This allows for the comparison of `Button` to identify itself.

UI: make `Button` conform to `Equatable`

---

Sources/CMakeLists.txt
Sources/UI/AlertAction.swift
Sources/UI/AlertController.swift

This adds the skeleton for an `AlertController` to present an alert
which is generated from the definition created by the controller derived
as a simple dialog.

UI: sketch in `AlertController`

---

Examples/Calculator/Calculator.swift

The size of the window is now correctly computed.  The result is that
the workarounds for the window size no longer need to be applied.  The
frame that is specified now specifies the proper client area of the
window.

Calculator: correct window size

---

Sources/Support/Rect+UIExtensions.swift

Mark the declaration as `internal` rather than the extension.

Support: stylistic changes for access control

---

Sources/UI/View.swift

We internally assume that the `hWnd` for the `View` is always valid.
The window should only be destroyed when the instance is being
deallocated.  As a result, the `hWnd` should always be non-nil.  This
previously caused issues as the `CreateWindowExW` would accidentally
return `nil` and we would not notice it the return type is marked as
nullable.

UI: make `View.hWnd` implicitly unwrapped

---

Sources/UI/View.swift

When constructing a view, always set the default font.  Although in some
cases this is meaningless (e.g. `Window`), it ensures that all controls
use the preferred system font of the default system font size.

UI: initialize the default font

---

Sources/Support/PropertyWrappers.swift

Adjust the implementation to return nil if there is no text rather than
an empty string.  This enables differentiating between an empty string
and no text being set.

Support: adjust `_Win32WindowText` property wrapper

---

Examples/UICatalog/UICatalog.swift
Sources/UI/TextField.swift

Since we model the `TextField` using a RichEdit, we cannot use the
simpler approach of using `EM_SETCUEBANNER` to render the placeholder
text.  Instead, rely on the fact that we subclass the window to override
the `WM_PAINT` event and render the placeholder text manually on top of
the default rendering.

UI: add support for placeholder text in `TextField`

---

Sources/UI/Window.swift

The toplevel windows now only allow closing but are resizeable still.
This removes the clutter in the title bar and behaves more as desired.

UI: remove minimize/maximize boxes from the titlebar

---

Sources/CMakeLists.txt

This just categorises them better to be more homogeneous and easier to
follow.

build: split up `Application` and `UI` sources

---

Sources/UI/TraitCollection.swift

Rather than re-computing the value each time, cache the value.  Although
this means that the value can be out-of-date, we should rely on Windows
notifications to update the traits as appropriate.

UI: make `TraitCollection.current` a stored property

---

Sources/UI/View.swift

This ensures that any windows that are not in use are cleaned up.
Although the need for this is unlikely common, it is better to ensure
that we do not leak any windows.

UI: explicit destroy the window when a `View` is deinited

---

Sources/CMakeLists.txt
Sources/Support/Error.swift
Sources/Support/WinSDK+Extensions.swift

This type is inspired by the work on Swift NIO.  It attempts to track
provenance of the error code and provide a human readable form of the
error message when converted to a string.  This should help track the
various error codes and domains in Windows.

Support: add new `Error` type

---

Sources/UI/Button.swift

This avoids spelling out the button window class name.  Although this is
unlikely to change, it is better from a hygiene perspective.

UI: use the constant for the Button Window Class

---

Sources/UI/Label.swift
Sources/UI/Switch.swift

This cleans up the last of the cases where we spelt out the names of the
window classes in the code base.  With the recent cleanups in the Swift
compiler, we no longer need these.

UI: avoid spelling out the class names for `Switch` and `Label`

---

Sources/CMakeLists.txt
Sources/Support/String+UIExtensions.swift

Reduces the overhead of the conversion by avoiding the unnecessary
zero'ing.  Rename the file to indicate that this is adding extensions to
String.

Support: remove redundant zero'ing

---

Sources/UI/View.swift

This gathers the view hierarchy related functions and variables.  It
also adds a new variable which is the `window` to which the view
belongs.  Note that this is currently not available for use.  These are
all read-only externally and are only writable within the class, so
remove the misleading comment.

UI: reorder the view hierarchy management declarations (NFCI)

---

Sources/UI/Device.swift

Avoid some unnecessary zero'ing when querying the system name.

UI: avoid unnecessary zero'ing in `Device.current.name`

---

Sources/UI/Screen.swift

Fix the typo in `device`.  Adjust stylistic annotation of internal
extensions.

UI: fix a typo in a variable name in `Screen` (NFC)

---

Sources/Application/Application.swift
Sources/Application/ApplicationDelegate.swift
Sources/Application/ApplicationMain.swift
Sources/Application/LaunchKeyOptions.swift
Sources/CMakeLists.txt

Restructure the files a bit to be easier to locate the code.  As the
application lifecycle code grows, this is important to aid with
discoverability of the code.

Application: split out the LaunchOptionKeys and move main

---

Sources/Application/ApplicationMain.swift

This is currently unused, remove the message hook.  When needed, it
would be possible to restore it.

Application: remove message proc hook

---

Sources/Application/Application.swift
Sources/Application/ApplicationDelegate.swift
Sources/Application/ApplicationMain.swift
Sources/UI/Scene.swift
Sources/UI/SceneConfiguration.swift
Sources/UI/SceneSession.swift

This allows round-tripping through the application delegate to get
configuration for the scenes.  This needs to be enhanced to permit
the client to modify the WindowScene's `sizeRestrictions` informing
the window construction to permit resizing.

Application: wire up some of the Scene delegate callbacks

---

Sources/UI/WindowScene.swift

Ideally this will be based on the device configuration.  Surface Neo and
Surface Duo devices should permit multiple windows via scenes, but
should restrict the window resizing.

UI: unrestrict window resizing for now

---

Sources/Application/ApplicationMain.swift
Sources/UI/Scene.swift
Sources/UI/SceneDelegate.swift
Sources/UI/SceneSession.swift
Sources/UI/WindowScene.swift

This corrects the startup events to make the scene setup later and
correct the extension points to execute at the right time to enable
applications to configure the scene.  It temporarily removes the
tear down path as it still does not seem to entirely make sense.  The
scene and scene delegate is now configurable via code.

Application: correct the order of callbacks

---

Sources/Application/ApplicationMain.swift
Sources/UI/SceneConfiguration.swift
Sources/UI/SceneSession.swift

Deserialise the scene configuration from the Info.plist in the bundle.
Use this to deserialise `SceneClass` and `SceneDelegate` default values
when starting up the application.

Application: deserialise `SceneClass` and `SceneDelegate`

---

Sources/UI/Stepper.swift
Sources/UI/TextView.swift
Sources/UI/View.swift

Extracted from https://github.com/compnerd/swift-win32/pull/158.
I renamed the property into `gwlStyle` instead of `GWL_STYLE` to avoid clashing with the WinSDK constant, @compnerd please let me know if you still want it to be named in caps.

Extract `View.gwlStyle` property

---

Sources/Application/ApplicationMain.swift

Calling SetWindowsHookExW with 0 as thread id will load SwiftWin32.dll in all GUI processes, but UnhookWindowsHookEx does not guarantie to unload that library at all.
In my case, actualy, I got high CPU usage on many processes like Explorer.exe, and 100% CPU usage on user session after application (Calculator.exe) termination.
Better to pass the id of the main thread to SetWindowsHookExW and set hooks for the application that calls ApplicationMain

Properly install/remove hooks

---

Sources/CMakeLists.txt
Sources/Support/WindowsHandle+UIExtensions.swift
Sources/UI/Font.swift
Sources/UI/Screen.swift

This centralizes the definitions for the handling of Windows Handles to
make them easier to find.

Support: split out the `WindowsHandle` extensions

---

Sources/UI/Device.swift

Rather than creating an alternate name, use the well defined name
`landscapeLeft`.

Device: remove internal `landscape` alias (NFC)

---

Examples/UICatalog/UICatalog.swift

The height of the label was greater than the stepper.  This would result
in a weird region of incorrect painting when adding a new control to the
demo.

UICatalog: adjust label height

---

Sources/UI/View.swift

This enables resizing a view by setting its `frame` property.  This
addresses an existing TODO item required for enabling building a
TableView.

UI: enable setting the frame of a view

---

.gitattributes

Mark swift files as text and use Unix line endings.

git: add `.gitattributes`

---

Sources/UI/TableView.swift

We can use the sentinel `-1` for the index to indicate that the item
should be added to the end.  This avoids the need for special counting
and will become more important once header and footer cells are
inserted.

UI: remove unnecessary variable in table view processing

---

Sources/Application/ApplicationMain.swift
Sources/Support/WinSDK+Extensions.swift

These changes allow us to use the RunLoop timers/sources and/or the Dispatch queue API on the main queue.
In future we should use CFRunLoop API to handle Win32 messages
_CFRunLoopSetWindowsMessageQueueMas and _CFRunLoopSetWindowsMessageQueueHandler wrapped in Swift style API

Improve Application main loop

---

Sources/UI/View.swift

This enables the creation of an empty view which can be used to build
general views that are not control views.

UI: support creating an empty view

---

Sources/Application/ApplicationMain.swift
Sources/Support/BatteryMonitor.swift
Sources/UI/Device.swift
Sources/UI/Font.swift
Sources/UI/TableView.swift
Sources/UI/TraitCollection.swift
Sources/UI/View.swift
azure-pipelines.yml

Updated calls to `GetLastError()` to use the Error Struct's `init(win32 error: DWORD)` to allow for more meaningful output with the Error Description.
Fixes #165

Update uses of GetLastError() to be called within the win32 init of Error

---

Sources/Application/ApplicationMain.swift

This reverts commit 8706996e99610a0cf462501756a666986daca3ac.
With this change UICatalog immediately exits upon launch rather than
continuing to pump the main loop.  The application launch completes
successfully as the key window is rendered, but then terminates shortly
thereafter.  Revert the change until the mainloop can be pumped.

Revert "Improve Application main loop"

---

Sources/UI/Device.swift

Rather than using a stored property, use a computed variable.

Device: stylistic change for notification names

---

Sources/UI/View.swift

Hookup the observation hook for enabling subviews to observe the
additional of a subview.  This can be potentially useful for resizing
windows when new content is added.

UI: enable derived views to observe sub-view addition

---

Sources/UI/TextField.swift
Sources/UI/TextView.swift
Sources/UI/View.swift

This property represents the Window's `GWL_EXSTYLE` property, mirroring
the ease of access of `GWL_STYLE`.

UI: introduce the internal `GWL_EXSTYLE` property

---

Sources/UI/TextView.swift

We do not currently use the subclassing to perform any actions.  Remove
the subclass until it is needed.

UI: remove unnecessary subclassing for `TextView`

---

Sources/UI/ViewController.swift

This makes a `ViewController` a `Responder` to allow wiring up the
events up the chain from the control to the application.

UI: make `ViewController` conform to `Responder`

---

Sources/CMakeLists.txt
Sources/UI/FontMetrics.swift
Sources/UI/Label.swift
Sources/UI/TextField.swift
Sources/UI/TextView.swift
Sources/UI/View.swift

…sting`
`View` should conform to `TraitEnvironment` since it is impacted by the
current device traits.  This also allows `Label`, `TextField`, and
`TextView` implement the `ContentSizeCategoryAdjusting` conformance by
being able to observe trait environment changes, enabling them to adjust
the font if necessary.  This requires the addition of `FontMetrics` to
perform the scaling.
`FontMetrics.scaledFont(for:maximumPointSize:compatibleWith:)` needs to
be implemented still and is left for future work.

UI: `View` conforms to `TraitEnvironment`, `ContentSizeCateogryAdjusting`

---

Sources/UI/Button.swift
Sources/UI/View.swift

Rather than making `Button` equatable, make all views equatable by
making `View` equatable.  This is safe to do as we check the underlying
`hWnd` as a means of checking equality.

UI: make `View` equatable

---

Sources/UI/FontDescriptor.swift

Add the `FontDescriptor` class which is needed to complete the `Font`
interfaces as well as implement
`FontMetrics.scaledFont(for:maximumPointSize:compatibleWith:)`.

UI: add `FontDescriptor`

---

Sources/Application/ApplicationMain.swift

Ensure that we always create a scene type, defaulting to a WindowScene
if no scene is specified in the configuration.

Application: correct initialization of scene

---

Sources/UI/SceneConfiguration.swift

If no name was provided and the scene configuration is deserialised
from the Info.plist, switch to the desired name.

UI: correctly track name for the scene configuration

---

Sources/UI/SceneDelegate.swift

Correct the typo in the argument label.

UI: correct method name (NFCI)

---

Sources/CMakeLists.txt
Sources/Support/Point+UIExtensions.swift
Sources/UI/Window.swift

By intercepting this in the subclass procedure for Window, we can
restrict the client area sizing.  This allows us to honour the window
size request from the application as specified by the scene delegate.
Note that the client area must be adjusted to the window area when
limiting the tracking size of the Window as otherwise, the non-client
area will eat into the window shrinking the available client area.

UI: handle `WM_GETMINMAXINFO` in `Window`

---

Examples/UICatalog/UICatalog.swift

Rename the main application class to reflect the name of the executable.

UICatalog: rename `SwiftApplicationDelegate` to `UICatalog`

---

Examples/UICatalog/CMakeLists.txt
Examples/UICatalog/Info.plist
Examples/UICatalog/UICatalog.swift

This alters the demo to use scene-based management for the window
sizing.  This allows the removal of additional WinSDK constants.

UICatalog: adopt scene-based management

---

Sources/Application/ApplicationMain.swift

It is possible that the ApplicationDelegate and the SceneDelegate are
actually the same class (and possibly even the Application).  Do not
instantiate new copies of the class if the types are related, opting
instead to reference the existing instance of the appropriate type.

Application: avoid unnecessary delegate constructions

---

Sources/Support/Error.swift

This corrects the use of `FormatMessageW`, and simplifies the code by
increasing the shared portions of the description generation.

Support: correct Error code to description conversion

---

Sources/CWinRT/WinRTAugmentation.cc
Sources/CWinRT/XAMLSupport.c

Use the license identifier rather than inline license text.

CWinRT: replace inline license text with SPDX

---

Package.swift

Enable building the HelloWorld demo with swift package manager.
Although this is still not the recommended build style, it enables the
path for the curious.

build: add HelloWorld demo to Package.swift

---

Package.swift

Force the swift-log dependency when building with Swift Package Manager
as it does not afford the same flexibility as CMake does with options.

build: make swift-log a hard requirement for SPM builds

---

Sources/UI/View.swift

Invoke `SetWindowSubclass` for all kinds of views in `View.init`, set the default `SUBCLASSPROC` for views which do not provide a custom implementation. This will allow `View` to handle popup menu events like `WM_CONTEXTMENU`.

UI: add `SUBCLASSPROC` for `View`

---

Sources/UI/View.swift

Register views for touch events.  This will allow touch even processing
in the subclassed windows.

UI: register View for touch events

---

Package.swift
Sources/SwiftUIWin32/Application.swift
Sources/SwiftUIWin32/EmptyView.swift
Sources/SwiftUIWin32/Never+SwiftUI.swift
Sources/SwiftUIWin32/Scene.swift
Sources/SwiftUIWin32/SceneBuilder.swift
Sources/SwiftUIWin32/View.swift
Sources/SwiftUIWin32/ViewBuilder.swift
Sources/SwiftUIWin32/WindowGroup.swift

Add some of the SwiftUI-like DSL building structuring for sketching out
a possible implementing of a DSL based UI construction layer built atop
of Swift/Win32.

SwiftUIWin32: add initial attempt to build a UI DSL

---

Package.swift
Sources/Application/ApplicationMain.swift
Sources/CMakeLists.txt

Use the address of a variable within the module to identify the module
via the `GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS`.  This is more
reliable, and enables the library to be used in both static and dynamic
form.

Application: use an address to identify SwiftWin32

---

Sources/UI/View.swift

Use the `GWL_STYLE` and `GWL_EXSTYLE` properties rather than using
`GetWindowLongPtrW` and `SetWindowLongPtrW` explicitly.  This makes it
easier to follow the logic and centeralises the error handling.

UI: simplify the style management on view adoption

---

Sources/UI/View.swift

This ensures that when the size of a view is changed, we scale it
properly rather than keeping it at 100% on a HiDPI display with a
different scale.

UI: always scale the view for the DPI

---

Sources/UI/Button.swift

Move the event to up rather than down.  This matches the user's
expectation better (that it is registered upon completion rather than
during a press).
Continue the default handling to correct the animation of the press of
the button.

UI: tweak notification for Button press

---

Sources/UI/CellConfigurationState.swift
Sources/UI/ConfigurationState.swift

Add the basis for the definitions for the configuration states needed to
build the content configurations for list views which will allow
extending the table view.

UI: add protocols for Configuration States

---

Sources/UI/Button.swift

The `Button` should allow multi-line labels by default.

UI enable multi-line buttons by default

---

.gitignore

Ignore the `Packages/` directory and the `package.resolved` file from
SPM.

.gitignore: ignore more SPM artifacts

---

Sources/CMakeLists.txt
Sources/UI/Event.swift
Sources/UI/Responder.swift
Sources/UI/Touch.swift

Now that Windows will provide touch event information to the window via
the `WM_TOUCHINPUT` event, start adding the extension points for
handling the touch events.

UI: wire up extension points for handling touch events

---

Package.swift
Sources/CMakeLists.txt
Sources/UI/Device.swift
Sources/UI/Screen.swift

Now that the Swift compiler supports the MS anonymous structures
extension, use that in place of the workaround of naming the anonymous
fields.  This makes most instances of the code easier to read and
actually makes one of the type-casts explicit in the code.

UI: allow use of MS extension for anonymous structs

---

Examples/UICatalog/CMakeLists.txt
Sources/CMakeLists.txt

The project now requires a snapshot from 10/23 or newer.  Remove the
backwards compatibility support from the build.

build: remove workaround for older compiler releases

---

Sources/SwiftWin32/UI/WindowSceneDelegate.swift

Make an optional property actually so, addressing the TODO in the
definition.  This cleans up the documentation while there.

UI: address TODO in `WindowSceneDelegate`

---

Sources/SwiftWin32/Application/ApplicationDelegate.swift
Sources/SwiftWin32/Application/ApplicationMain.swift

Use the application state notification hook to monitor for changes to
the application status.  This allows for background notification
handling.

Application: monitor application suspension

---

Sources/SwiftWin32/CMakeLists.txt

This protocol provides a set of methods for converting between different
frames of reference on a screen.

UI: add `CoordinateSpace` protocol

---

Examples/Calculator/Calculator.swift
Examples/Calculator/Info.plist
Package.swift

Convert from ApplicationDelegate to SceneDelegate to construct the
window.  This allows us to remove the usage of WinSDK in the
application.
Fixes: #237

Calculator: convert to scene layout

---

Examples/Calculator/Calculator.swift

Use these to control the conversion rather than directly using
`NSNumberFormatter`.  This reduces a bit of the complexity in the code
for readability.

Calculator: use `NSDecimalNumber` and `Decimal`

---

CMakeLists.txt
Sources/CMakeLists.txt

Build SwiftCOM so that we can use that to initialize the COM threading
model within the application.

build: add Swift/COM module to the build

---

Sources/SwiftWin32/UI/Control.swift

Add some documentation comments to the `Control` interface.
Additionally, convert a number of constant values to `var` rather than
`let` constants to avoid storage.

UI: add documentation comments and convert constants to vars

---

CMakeLists.txt
Package.swift
Sources/SwiftWin32/Application/ApplicationMain.swift
Sources/SwiftWin32/CMakeLists.txt

COM is intended to be used to access WIC (Windows Imaging Component) to
allow decoding (and potentially encoding) of images.  Use Swift/COM to
access nicer wrappers over the raw C interfaces for COM.

Application: initialize COM

---

Sources/SwiftWin32/UI/ViewControllerTransitionCoordinatorContext.swift

Convert some constants to computed properties instead of stored
properties.  Additionally, take the opportunity to add documentation
comments to the protocol.

UI: convert a few constants to computed properties (NFC)

---

Examples/UICatalog/UICatalog.swift

SwiftPM generates a `Bundle.module` field, which should be used for accessing resources associated with the current target.
Using `Bundle.main` causes a runtime error in this case, since the requested image URL is `nil`.

UICatalog: use the correct bundle when building with SwiftPM

---

Sources/SwiftWin32/UI/Window.swift

If the scene restricts the window to the same minimum and maximum
dimensions, prevent the user from resizing the window bounds.  We would
previously remove the minimize and maximize buttons but would still
silently allow the user to resize the window bounds from the edge.
Unset the `WS_SIZEBOX` window style to prevent this.

UI: prevent resizing of the window in fixed mode

---

Sources/SwiftWin32/UI/Scene.swift

Ensure that we keep a reference to the `Session` for which the `Scene`
was constructed.

UI: track the `session` in `Scene`

---

Sources/SwiftWin32/UI/FontDescriptor.swift

Use computed properties for constants for various font attributes.

UI: convert FontDescriptor `let`s to computed variables

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift
Sources/SwiftWin32/UI/SceneDelegate.swift
Sources/SwiftWin32/UI/Window.swift

Wire up `WM_ACTIVATE` to trigger the delegate updates for window
resigning foreground and becoming active.

UI: notify the scene delegate on window activation

---

Sources/SwiftWin32/Application/ApplicationDelegate.swift
Sources/SwiftWin32/UI/SceneDelegate.swift
Sources/SwiftWin32/UI/TableViewDataSource.swift
Sources/SwiftWin32/UI/View.swift

Use similar language throughout the project's doc comments relating to
informing the delegate.

docs: homogenise documentation style (NFC)

---

Sources/SwiftWin32/Application/Application.swift

Since `supportsMultipleScenes` is non-static, there's no need to access through the `shared` instance.

Application: remove unnecessary qualifier

---

Sources/SwiftWin32/Platform/OrientationSensor.swift

A `REFGUID` is effectively `GUID *`.  Ensure that we dereference it
before checking the value.

platform: dereference the REFGUID when checking

---

Sources/SwiftWin32/Platform/BatteryMonitor.swift
Sources/SwiftWin32/Support/WinSDK+Extensions.swift

The ability to check for `GUID` equality is rather common on Windows.
Move the internal implementation from the `BatteryMonitor` into the
WinSDK extensions and make it available internally to the module.

Support: hoist GUID equality into the Support layer

---

Package.swift

SwiftPM prints this warning when trying to build the package:
```
'SwiftWin32' C:\Users\Egor Zhdan\swift-win32: warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
C:\Users\Egor Zhdan\swift-win32\Sources\SwiftWin32UI\CMakeLists.txt
```

build: fix SwiftPM warning

---

Sources/SwiftWin32/UI/TableViewCell.swift

A `TableViewCell` acts as a slab allocation, where the allocation can be
re-used.  This adds the cleanup extension point that allows for
extending the cleanup routine to ensure that the cell can be used to
render a new item.

UI: add `prepareForReuse` to `TableViewCell`

---

Sources/SwiftWin32/Application/ApplicationDelegate.swift
Sources/SwiftWin32/UI/TableViewDataSource.swift
Sources/SwiftWin32/UI/TextField.swift

Address the recent warning that was added for deriving protocols from
`class`.

SwiftWin32: conform protocols to `AnyObject`

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Support/WindowsHandle+UIExtensions.swift
Sources/SwiftWin32/UI/ContextMenuConfiguration.swift
Sources/SwiftWin32/UI/ContextMenuInteraction.swift
Sources/SwiftWin32/UI/Menu.swift
Sources/SwiftWin32/UI/MenuElement.swift
Sources/SwiftWin32/UI/View.swift

This change adds support for basic context menus (attached to a `View` instance) and window title menus. For both types of menus submenus are supported.

UI: support showing basic context menus

---

Sources/SwiftWin32/UI/Menu.swift

Store `Identifier` & `Options` as fields of `Menu`. This will be useful for supporting inline submenus.
It also matches the macCatalyst interface.

UI: expand Menu public interface

---

Sources/SwiftWin32/UI/Menu.swift

Add some documentation to properties for `Menu`.  Make an internal
property more accessible and add a stub for a function that should be
added in the future.

UI: add some documentation to menu properties

---

Sources/SwiftWin32/UI/View.swift

Add a hook for observing moving between `Window`s.

UI: add missing view observation hooks

---

Sources/SwiftWin32/UI/View.swift

Shuffle the members around and add some additional documentation for the
members.  Add a stub for a missing method on `View`.

UI: reorganise some of the `View` members (NFC)

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift

This adds the mirroring half of `LOWORD` of `HIWORD` to easily decompose
`lParam` values in window message handlers.

Support: add definition of `HIWORD`

---

Sources/SwiftWin32/CG/Rect.swift
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Support/Point+UIExtensions.swift
Sources/SwiftWin32/Support/Rect+UIExtensions.swift
Sources/SwiftWin32/Support/Size+UIExtensions.swift

It is very common to construct these types from various fixed-width
values.  Provide a generalized constructor to convert any fixed-width
integer type to the proper type.

SwiftWin32: add Size,Point,Rect convenience initializers

---

Sources/SwiftWin32/UI/Menu.swift
Sources/SwiftWin32/UI/MenuElement.swift
Sources/SwiftWin32/UI/View.swift

Split out the separator handling for `Win32MenuElement` into an
extension, reducing the amount of content in the main definition.
Replace the `of` "constructor" to a `convenience init` on
`Win32MenuElement`.
Rename the `win32ContextMenu` to `menu` in `View`.
Ad a generic helper to identify and cast the interaction from the view's
interactions.
Simplify the `WM_CONTEXTMENU` routine by always clearing the `menu`
field, replacing the menu, avoiding two separate paths.  Collapse the
access of the actions from the context menu configuration provided by
the delegate into a single chained query.  If one is provided, then only
do we create a new menu.

UI: refactor, simplify menu handling

---

Sources/SwiftWin32/UI/ContextMenuInteractionDelegate.swift
Sources/SwiftWin32/UI/Interaction.swift

This resolves the deprecation warnings for class constrained protocols,
by replacing the `class` inheritance with `AnyObject`.

SwiftWin32: replace inheritance from `class` with `AnyObject`

---

Package.swift
Tests/AutoLayoutTests/AutoLayoutTests.swift
Tests/LinuxMain.swift

Add some test harness for enabling testing `LayoutConstraint`.  The
layout constraint paths are not rendering related and can be tested more
readily.

Tests: add an initial test harness setup

---

Examples/UICatalog/UICatalog.swift
Sources/SwiftWin32/UI/View.swift

Rather than storing a scaled version of the frame, store the unscaled
frame.  This ensures that we do not accumulate error over multiple
scaling. This actually uncovered rendering issues within UICatalog where
the scaling would resize the controls to be taller than intended.
The change also now makes the spacing expected and consistent across all
the controls.

SwiftWin32: adjust the stored frame value

---

Sources/SwiftWin32/UI/TableView.swift
Sources/SwiftWin32/UI/TextField.swift
Sources/SwiftWin32/UI/View.swift

When the view is reparented, we cannot simply query the frame and use
the value.  We must scale the value appropriately for the current DPI
scaling.  This is required since we store the requested scale rather
than the rendered scale (which allows greater flexibility).
Fixes: #315

UI: adjust client area during reparenting

---

Sources/SwiftWin32/UI/Color.swift

Make `Color` conform to `Hashable`.  Minor stylistic change for the
equality function, making it a `static` function in the conformance
rather than freestanding to make it easier to locate.

UI: make `Color` hashable

---

Examples/UICatalog/CMakeLists.txt
Examples/UICatalog/UICatalog.swift

Ensure that we copy the resource into the main bundle (output
directory).  Make the failure to load the resource more explicit as it
was confusing to others.
Fixes: #330

build,UICatalog: correct the bundle layout

---

Sources/SwiftWin32/UI/View.swift

Reorder a couple of the groups around for `View`.

UI: shuffle groups around in `View` (NFC)

---

Sources/SwiftWin32/UI/TextField.swift

When rendering the placeholder text, we need to swap out the font for
the drawing context to ensure that we get the proper font for the
rendering.  This also ensures that the placeholder is actually rendered
with the same text as the content.
Fixes: #318

UI: scale the font for the TextField placeholder

---

Sources/SwiftWin32/CG/Vector.swift
Sources/SwiftWin32/CMakeLists.txt

Add the `Vector` type to represent a 2D vector.

CG: add `Vector` type

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusAnimationCoordinator.swift
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusEnvironment.swift
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusItem.swift
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusItemContainer.swift
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusMovementHint.swift
Sources/SwiftWin32/UI/Focus-Based Navigation/FocusUpdateContext.swift

This adds some of the basic structures for the focus based navigation
infrastructure.  This is meant to support navigation with alternate
input systems (e.g. gamepads).

UI: add focus based navigation types

---

Sources/SwiftWin32/UI/TableViewCell.swift

Add the interfaces to control the editing state of a `TableViewCell`.

UI: add editing interfaces to `TableViewCell`

---

Sources/SwiftWin32/UI/Axis.swift
Sources/SwiftWin32/UI/PointerInteraction.swift
Sources/SwiftWin32/UI/PointerInteractionAnimating.swift
Sources/SwiftWin32/UI/PointerInteractionDelegate.swift
Sources/SwiftWin32/UI/PointerRegion.swift
Sources/SwiftWin32/UI/PointerRegionRequest.swift
Sources/SwiftWin32/UI/PointerStyle.swift

This starts adding some of the structure necessary to specialise the
interactions for pointers and touch interfaces simultaneously.

UI: add `PointerInteraction` structures

---

Sources/SwiftWin32/Views and Controls/View.swift

Add the necessary interfaces for drawing and resizing the Views.  This
should allow the removal of the hard coded handling for table view in
UICatalog and setup the autolayout paths.

View: add resizing/drawing interfaces

---

Examples/UICatalog/UICatalog.swift
Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift
Sources/SwiftWin32/Views and Controls/Table Views/TableViewCell.swift

Compute the frame for the cell at runtime when the cell is populated.
This allows us to dynamically size for the content.

Table View: compute the cell size automatically

---

Examples/UICatalog/UICatalog.swift
Sources/SwiftWin32/Application/ApplicationMain.swift
Sources/SwiftWin32/Windows and Screens/Window.swift

Convert the application notifications to the scene notifications.
Additionally, post additional notifications on events as appropriate.
In the case that the application and scene based both are subscribed to,
the scene based notifications are preferred.

UI: improve application lifecycle handling & notifications

---

Sources/SwiftWin32/Windows and Screens/Window.swift

The window activation should map to `sceneWillEnterForeground` not,
`sceneDidBecomeActive` which indicates that the application was
foregrounded.  We were previously incorrectly reporting the event.

UI: correct delegate invocation for window activation

---

Sources/SwiftWin32/App and Environment/ApplicationDelegate.swift

Add a definition of `InterfaceOrientationMask` which is intended to be
used by `ViewController`.

Application: add `InterfaceOrientationMask`

---

Sources/SwiftWin32/AutoLayout/LayoutPriority.swift

Use computed properties for the constants rather than stored properties.
The values are completely trivial and the storage is unnecessary.

AutoLayout: convert stored properties into computed properties

---

Sources/SwiftWin32/AutoLayout/LayoutAnchor.swift

Fix a typo: the label should have been:
`LayoutAnchor.constraint(lessThanOrEqualTo:constant:)`

AutoLayout: correct label for

---

Sources/SwiftWin32/AutoLayout/LayoutAnchor.swift

There is a definition which takes an optional constraint.  Implement the
function as an alias instead.

AutoLayout: use dispatching to reduce duplication

---

Sources/SwiftWin32/AutoLayout/LayoutDimension.swift

Use the item itself being bound rather than `self`.

AutoLayout: correct `LayoutDimension` construction

---

Sources/SwiftWin32/Views and Controls/Button.swift
Sources/SwiftWin32/Views and Controls/Switch.swift

Trigger additional notifications for buttons.  In particular, the
`BN_CLICKED` is a useful notification to receive to trigger events
(`.defaultAction`) on `Button`.

Views and Controls: add `BS_NOTIFY` style

---

Sources/SwiftWin32/Windows and Screens/Window.swift

Correct the case for the notification name.  No functional change.

Windows and Screens: adjust notification name

---

Sources/SwiftWin32/Application/ApplicationMain.swift

Ensure that we attempt to log any failures from `InitCommonControlsEx`.

Application: log an error on `InitCommonControlsEx` failure

---

Examples/HelloWorld/HelloWorld.swift

- Main motivation: The "Hello World" example does not show a "hello world" message. This commit fixes this.
- Other motivation: I remember that "hello world" examples in GUI frameworks usually show at least a label.

HelloWorld example: added a title and a label

---

Examples/Calculator/CMakeLists.txt

- Before the fix: The calculator app build successfully but does not show any window
- Cause: info.plist was not copied into ?binary?
- The fix: the info plist copy command is added to calculator's CMakeLists.txt. CMakeCache needs to be invalidated.

Calculator: fix missing info.plist

---

Package.swift

It's now possible to explicitly declare executable targets in SwiftPM, starting from Swift 5.4.
This change removes `main.swift` files in the example targets – SwiftPM now treats them as executable even without `main.swift`.

build: use new `executableTarget` API

---

Sources/SwiftWin32/Views and Controls/Stepper.swift

Rather than force unwrapping the parameter, silently drop the message if
the value is unexpectedly missing.

UI: make stepper subclass handling safer

---

Sources/SwiftWin32/Views and Controls/View.swift

The parent view has a strong reference to the child view.  However, the
child view also has a strong reference to the parent.  This constructs a
circular reference.  Make the parent reference weak as the parent window
owns the child.  We similarly want to avoid the strong reference to the
Window object as the Window object owns the reference to the views.

UI: avoid circular references

---

.gitattributes
Documentation/BundleLayout.md

Add some documentation describing the bundle layout format which is both
expected by CoreFoundation and thus by Foundation as well as the
Swift/Win32 framework.  This is a minimal description which should
hopefully make it easier for others to contribute.

Documentation: add some documentation about bundle layouts

---

Sources/SwiftWin32/Application/Information.swift

The options keys in `Info.plist` nor the classes in the framework
currently are not prefixed.  Follow suit to make everything more
consistent.

Application: rename `NSPrincipalClass` to `PrincipalClass`

---

Sources/SwiftWin32UI/EmptyView.swift
Sources/SwiftWin32UI/Never+SwiftUI.swift

For the case where the `Body` type is `Never`, we can simply synthesize
the default member for the `View` type.

SwiftUI: add a default implementation for `body`

---

Sources/SwiftWin32/Text Display and Fonts/FontMetrics.swift

`traitCollection` is currently used as
`FontMetrics.scaledFont(for:maximumPointSize:compatibleWith:)` is not
yet implemented.  Silence the warning by assigning the result to the
blackhole.

SwiftWin32: silence an annoying warning

---

Sources/SwiftWin32/Images and PDF/Image.swift

Add definitions for:
- `Image.Configuration`
- `Image.SymbolWeight`
- `Image.SymbolScale`
- `Image.SymbolConfiguration`
These are intended to be used for subsequent `ListContentConfiguration`
work.

Images and PDF: add additional Image configuration

---

Sources/SwiftWin32/Appearance Customization/Configurations/ListContentConfiguration.swift

Add a definition of `ListContentConfiguration`.  This is meant to
support the `TableViewHeaderFooterView`.

Appearance Customization: add `ListContentConfiguration`

---

Sources/SwiftWin32/AutoLayout/LayoutConstraint+Cassowary.swift

This adds an internal extension to tie together the `LayoutConstraint`
type and the Cassowary simplex by allowing conversion of a
`LayoutConstraint` to a cassowary constraint.  This will enable building
up the constraint set to symbolically resolve the layout.

AutoLayout: begin adding support to create constraints

---

Sources/SwiftWin32/Appearance Customization/Configurations/ConfigurationState.swift
Sources/SwiftWin32/Appearance Customization/Configurations/ConfigurationStateCustomKey.swift
Sources/SwiftWin32/CMakeLists.txt

Split out the definition to a standalone file.

Appearance Customization: split out `ConfigurationStateCustomKey`

---

Examples/UICatalog/UICatalog.swift
Sources/SwiftWin32/App and Environment/Device.swift
Sources/SwiftWin32/App and Environment/TraitCollection.swift
Sources/SwiftWin32/Application/ApplicationMain.swift
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Menus and Shortcuts/MenuElement.swift
Sources/SwiftWin32/Platform/PropertyWrappers.swift
Sources/SwiftWin32/Platform/WindowClass.swift
Sources/SwiftWin32/Support/Array+Extensions.swift
Sources/SwiftWin32/Support/Logging.swift
Sources/SwiftWin32/Support/String+UIExtensions.swift
Sources/SwiftWin32/Text Display and Fonts/Font.swift
Sources/SwiftWin32/View Controllers/ViewController.swift
Sources/SwiftWin32/Views and Controls/Button.swift
Sources/SwiftWin32/Views and Controls/TextField.swift
Sources/SwiftWin32/Windows and Screens/Screen.swift

This is a slight improvement over the original name.  We want the wide
string variant (UTF-16 encoded C string).  Name this accessor `wide` as
Windows traditionally refers to these as "wide strings".

Swift/Win32: rename `LPCWSTR` to `wide`

---

Sources/CMakeLists.txt
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32UI/CMakeLists.txt
cmake/Modules/SwiftSupport.cmake

The Swift support in CMake has improved to the point where the only
missing piece is the support for `install(TARGET)`.  Emulate the
behaivour with `_install_target`.  Eventually, hopefully, this support
can be replaced with `install(TARGET)`.  Use the 5.4 support for
installing the module in the same manner on all targets.

build: update the Swift install rule

---

Sources/SwiftWin32/Support/Array+Extensions.swift

Add a `Array.remove(object:)` function to easily remove an element from
an Array which contains equatable entries.

Support: add `Array.remove(object:)`

---

Sources/SwiftWin32/AutoLayout/LayoutConstraint.swift

When a constraint is activated, the constraint shall be added to the
nearest common ancestor.  Inactivation of the constraint does the same,
except instead of adding the constraint, removes it.
This implementation uses a poor scan for finding the nearest ancestor.
However, this should be possible to improve in the future.

Autolayout: implement `active` handler

---

CMakeLists.txt
Sources/CMakeLists.txt
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32UI/CMakeLists.txt
cmake/Modules/SwiftSupport.cmake

The build files were missing a copyright header, add the missing header.
Backdate to when the files were initially added.

build: add a copyright header

---

Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift

The reloading of the data should clear the state of the tableview even
when the `dataSource` is `nil`.  We would previously continue to display
the stale data as the guard would return too early.

Table View: always reset the state on reload

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift
Sources/SwiftWin32/Views and Controls/Button.swift
Sources/SwiftWin32/Views and Controls/DatePicker.swift
Sources/SwiftWin32/Views and Controls/Label.swift
Sources/SwiftWin32/Views and Controls/ProgressView.swift
Sources/SwiftWin32/Views and Controls/Stepper.swift
Sources/SwiftWin32/Views and Controls/Switch.swift
Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift
Sources/SwiftWin32/Views and Controls/TextField.swift
Sources/SwiftWin32/Views and Controls/TextView.swift
Sources/SwiftWin32/Views and Controls/View.swift
Sources/SwiftWin32/Windows and Screens/Window.swift

The imported values are imported as `Int32` rather than `UInt32` which
makes general usage of the values more difficult.  Provide a local
representation which uses the `UInt32` type.

Support: add local overloads for type-conversion

---

Tests/AutoLayoutTests/AutoLayoutTests.swift

The `view` variable is not referenced after the construction, which and is stored to a weak var.  This permits the compiler to discard the variable.  Extend the lifetime explicitly to ensure that it exists for the duration of the test.

tests: correct lifetime issue

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift

The current WinSDK overlay provided definition is not properly
null-terminated, which causes an issue when trying to load the class.
This allows us to build and run properly even in debug mode.

Support: clean up `MSFTEDIT_CLASS`

---

Sources/SwiftWin32/Menus and Shortcuts/MenuSystem.swift

Use the same style for the NYI stub in this file as the rest of the
project.

Menus and Shortcuts: make the `fatalError` informative

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift
Sources/SwiftWin32/Views and Controls/View.swift

`WS_CAPTION` falls into the same category as the other window style
values - it is meant to be a DWORD.  In C/C++, the type is implicitly
converted, however, in Swift, it will not be.  Provide a DWORD overload
of the value.  For the cases where we need the value as a `LONG`, we can
explicitly use the `WinSDK.` prefix to retrieve the long typed value.
This cleans up most of the usage of the value.

WinSDK: add an overload for `WS_CAPTION`

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift

Re-order the declarations into the correct header, mark them transparent.
These should not be visible to the debugger, and should always be
inlined.

Support: reorder some extension declarations

---

Sources/SwiftWin32/Views and Controls/Label.swift

I believe that this is all that is needed to implement the `STN_CLICKED` event.
Example usage:
```
let label=  Label(frame: Rect(x: 0, y: 0, width: 1000, height: 32))
label.font = Font(name: "Consolas", size: Font.systemFontSize)
label.text = "Hello"
label.addTarget(self, action: pressMe(_:), for: .primaryActionTriggered)
window.addSubview(label)
func pressMe(_: Label?) {
MessageBoxW(nil, "Swift/Win32 Demo!".wide,
"Swift/Win32 MessageBox!".wide, UINT(MB_OK))
}
```

Views and Controls: dispatch actions for Label

---

Sources/SwiftWin32/Views and Controls/Label.swift
Sources/SwiftWin32/Views and Controls/View.swift

`WC_STATIC` control doesn't receive events like `WM_CONTEXTMENU`. To be able to handle those events, let's create containing views for `WC_STATIC` instances.

UI: add containing `View` for each `Label`

---

Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift

reloadData() in TableView currently does nothing except pad the TableView subviews with the new cells.
I needed to add a handle for WM_DeleteItem to the TableView proxy to handle deleting the old cells. This message is triggered by the LB_RESETCONTENT message at the top of reload data.
Test scenario in UICatalog:
```
@main
final class UICatalog: ApplicationDelegate, SceneDelegate {
...
var funStrings : [String] = ["Iggy", "David", "Lou"]
var funEnabled : [Bool] = [false, false, false]
lazy var funToggles : () -> [(Button) -> () -> Void] =
{
[unowned self] in
var myList : [(Button) -> () -> Void] = []
for i in 0..<funEnabled.count {
myList.append(
{
_ in
{ 
self.funEnabled[i] = !self.funEnabled[i]
self.tableview.reloadData()
}
}
)
}
return myList
}
}
extension UICatalog: …
```

reloadData() deletes cells currently in TableView and replaces them with new ones from TableViewDataSource

---

Sources/SwiftWin32/Views and Controls/View.swift

The adjusting of the `GWL_STYLE` should occur after the window has been
re-parented.  This adjusts the order accordingly.  This was found by
inspection while trying to resolve an issue introduced with #444.

View: adjust the order of `GWL_STYLE` adjustment when reparenting

---

Examples/UICatalog/UICatalog.swift

UICatalog: the stepper controls the number of rows of the table

---

Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift

I have found the reason the TableCells were hidden after reloadData() was called a second time. For the first call which occurs when the data source is initially assigned to the TableView, a call to window.makeKeyAndVisible() follows. makeKeyAndVisible() will then go through and make the TableView and its populated cells visible. On the second call to reloadData(), the call to makeKeyAndVisible() does not occur, and so it is necessary to manually set the Cells to Visible.

Only set isHidden when needed

---

Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift

This just cleans up the style around the `WM_DELETEITEM` to match the
rest of the file.

TableView: adjust spacing (NFC)

---

Sources/SwiftWin32/Views and Controls/Table Views/TableView.swift

When reloading the data from the datasource, suspend the redraw
operations.

TableView: suspend redraws during refresh

---

Sources/SwiftWin32/Views and Controls/Stepper.swift

This can be added back in when needed.  It is unlikely since the
messages get handled through the proxy for the dispatching.

Stepper: remove unused subclass

---

Sources/SwiftWin32/Touches, Presses, and Gestures/GestureRecognizer.swift
Sources/SwiftWin32/Touches, Presses, and Gestures/GestureRecognizerDelegate.swift

This adds the two base types for the hierarchy to support implementing
gesture recognizers.  This is meant to provide the proper interaction
detection for Label components.  Currently, Label incorrectly derives
from Control, when it should derive from View.
This works towards a solution for #442.

Gestures: add GestureRecognizer and GestureRecognizerDelegate

---

Sources/SwiftWin32/Views and Controls/ImageView.swift
Sources/SwiftWin32/Views and Controls/Label.swift

The default state of these objects is meant to have user interactions
disabled.  This updates the implementation to mark them appropriately.
This will break the current behaviour of the Label which will accept
input.  However, the longer term desire is for tap events to be detected
using TapGestureRecognizer, which when bound, requires the user enable
the user interactions.  This moves us in that direction.

Views and Controls: mark Label and ImageView as not having interactions

---

Sources/SwiftWin32/Views and Controls/TextView.swift

Ensure that we enable the extended text limit rather than remain
compatible with the old Rich Text implementation.

TextView: extend the text limit

---

Sources/SwiftWin32UI/CMakeLists.txt
Sources/SwiftWin32UI/Essentials/App.swift

This matches the SwiftUI model more accurately.

SwiftUI: rename `Application` to `App`

---

Sources/SwiftWin32UI/CMakeLists.txt
Sources/SwiftWin32UI/View Layout and Presentation/Group.swift

This adds the Group type and add a couple of associated extensions for
construction via `SceneBuilder`s.

SwiftUI: add initial definition for Group

---

Sources/SwiftWin32/App and Environment/Device.swift

This variable is a read-only public property, which is altered using
`beginGeneratingDeviceOrientationNotifications` and
`endGeneratingDeviceOrientationNotifications`.

UI: `Device.isGeneratingDeviceOrientationNotifications` is RO

---

Sources/SwiftWin32/Support/WinSDK+Extensions.swift

Convert the constants to nullable values as the C API is expecting
nullable values in the first place.  Furthermore, mark the values as
being `internal` and make them transparent.  This issue was identified
when trying to generate documentation.

Support: adjust the definitions for HKEY constants

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Event.swift

Add a definition for `Event.ButtonMask` to support building up
`TapGestureRecognizer`.

Event: add `ButtonMask`

---

Sources/SwiftWin32/Touches, Presses, and Gestures/TapGestureRecognizer.swift

This adds a definition forr `TapGestureRecognizer`.  This type
definition is required to wire up tap gesture recognition support for
`Label`s.

Touches, Presses, and Gestures: Add TapGestureRecognizer

---

Sources/SwiftWin32/Text Display and Fonts/Font.swift
Sources/SwiftWin32/Views and Controls/Table Views/TableViewDataSource.swift

These comments are not documentation comments but rather region markers.
Correct the comment leader to ensure that they do not get misused as
documentation when using a documentation generator.

Correct some regional markers

---

Sources/SwiftWin32/CG/AffineTransform.swift

Per your suggestion, I have decided to split the commit for hitTest() and convert() into different parts. I realized that CGAffineTransform from CoreGraphics includes an inverted function. So it makes sense to add it to AffineTransform as well.

Add inverted() to AffineTransform

---

Sources/SwiftWin32/CG/AffineTransform.swift

Convert the `AffineTransform.identity` property from a `let` property to
a computed property.  This has no impact on the ABI, but homogenizes the
declarations throughout the module.

CG: stylistic change for `identity` property

---

.github/workflows/windows.yml

In order to reduce the output spew when building to make issues more obvious, disable the verbose build output.

CI: use terse output by default

---

Sources/SwiftWin32/Drawing/Color.swift

Adjust the color region markers in Color to ensure that the region
markers are not treated as documentation.

Drawing: correct region markers in Color

---

Sources/SwiftWin32/Animation and Haptics/View Controller Transitions/ViewControllerTransitionCoordinatorContext.swift
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/UI/AnimationCurve.swift
Sources/SwiftWin32/Views and Controls/View.swift

This migrates the `AnimationCurve` to the right location.  It is meant
to be an enclosed type.  Take the opportunity to add some additional
documentation comments around the area.

View: rename `AnimationCurve` to `View.AnimationCurve`

---

Examples/Calculator/CMakeLists.txt
Examples/UICatalog/CMakeLists.txt

When building with CMake, merge the manifest into the binary via a
resource section.  This avoids an additional file which needs to be
distributed and explains how to perform this step.

build: merge the manifest into the modules with CMake

---

Sources/CMakeLists.txt

The dependent modules are meant to be pristine and do not impact the
build.  When building with CMake, we do not build the dependencies via
SPM.  Because the dependent projects have removed their CMake based
builds, we just simply re-create the sub-project here.  Because there
are meant to be no changes to these dependencies when building
Swift/Win32, we can simply glob the sources.  This avoids maintaining an
out-of-tree build for the project and manually updating the source list.
Furthermore, this matches the SPM based build more accurately.

build: use glob for dependent modules

---

Sources/SwiftWin32/View Controllers/ViewController.swift

The supported interface orientations is supposed to be
`allButUpsideDown` by default.  This was identified when looking at
further implementing the view controller management interfaces.

ViewController: change some of the default values

---

Sources/SwiftWin32/Views and Controls/View.swift

The bounds represents the coordinate space of the view.  It is the
region of the view which is actually rendered.  We do not currently
support setting the bounds, which allows for resizing the view around
the center by setting the size.  The origin of the view bounds may also
be altered, which will result in the area outside of the bounds being
clipped.

View: add the `bounds` property

---

Sources/SwiftWin32/Views and Controls/View.swift

Add the `transform` property for `View` which is meant to provide the
means for applying world transforms before rendering a view.

View: add `transform` property.

---

.github/workflows/windows.yml

Enable builds for 5.4+ to get additional test coverage.  This should hopefully allow us to track the oldest supported version of the toolchain.

CI: enable multi-version builds

---

README.md

Correct a typo in the build instructions with SPM.

README: correct instructions typo

---

README.md

We currently can build against the 5.4 release.  Reduce the restriction on a snapshot only toolchain.  With the additional test now, if we were to break the stable release support, we can consider reinstating the snapshot requirement.

documentation: permit use of stable release

---

Tests/CoreGraphicsTests/CoreGraphicsTests.swift

Thanks to the lack of the test cases, we had a latent issue in the
mid-point computation.

tests: add some tests for `Rect`

---

.github/workflows/lint.yml

This splits out the lint action to try the `pull_request_trigger`
trigger in the hopes that this will allow fork PRs to be linted.

CI: split out lint task

---

Sources/SwiftWin32/CG/Rect.swift
Tests/CoreGraphicsTests/CoreGraphicsTests.swift

This adds the implementation for `Rect.offsetBy(dx:dy:)` and supporting
functions.

Rect: add definition of `Rect.offsetBy(dx:dy:)`

---

Sources/SwiftWin32/CG/Rect.swift

The null rectangle is defined as `{DBL_MAX, DBL_MAX, 0, 0}`.  The
implementation was incorrectly implemented as
`{INFINITY, INFINITY, 0, 0}`.

Rect: correct the definition of `Rect.null`

---

Sources/SwiftWin32/CG/Rect.swift

Use a bit more functional style computation in the application of a
transformation.  Use a single pass to simultaneously compute the new
bounds of the rectangle.

Rect: refine `Rect.applying(_:)`

---

Sources/SwiftWin32/Views and Controls/View.swift

- `#if` conditions should be 0-column aligned and do not impact the
actual code being conditioned.
- Reflow some comments to better bin pack.
- Remove some bleeding whitespace.
- Re-indent some code for better 80-column fitting.

View: stylistic changes (NFC)

---

Sources/SwiftWin32/CG/Rect.swift
Tests/CoreGraphicsTests/CoreGraphicsTests.swift

This adds the `standardized`, `integeral`, `isEmpty` properties, the
`insetBy` method and fixes an oversight in the `applying` method.

Rect: add additional `Rect` interfaces

---

Tests/CoreGraphicsTests/CoreGraphicsTests.swift

Use `sqrt(ULP)` to measure nearness rather than a random empirical
value.  Reflow some of the text in the testcases.  Simplify using a
`typealias`.

Tests: clean up some of the CoreGraphics tests

---

Sources/SwiftWin32/CG/Rect.swift

This adds a default constructor and the special value of `infinite` to
`Rect`.

CoreGraphics: add some additional `Rect` methods

---

Sources/SwiftWin32/CG/Rect.swift
Tests/CoreGraphicsTests/CoreGraphicsTests.swift

This adds the `intersection` and `intersects` methods to `Rect`.

CoreGraphics: add support for intersection

---

Sources/SwiftWin32/CG/Rect.swift

This cleans up some whitespace issues and renames the equality function,
making it freestanding rather than a method on `Rect`.

Rect: clean up the out-of-line equality

---

Sources/SwiftWin32/CG/Rect.swift
Tests/CoreGraphicsTests/CoreGraphicsTests.swift

Adding the functions `contains()` functions to `Rect`, testing if a `Rect` contains a given `Point` or different `Rect`. The `Rect` case is implemented with two calls to the `Point` function for both the top left and bottom right corners.

Add contains() functions to Rect

---

Sources/SwiftWin32/CG/Rect.swift

Add the `RectEdge` enumeration which is used by the last missing
function: `Rect.divided(atDistance:from:)`.

CoreGraphics: add a definition of `RectEdge`

---

README.md

Hi :)
I would like to contribute to Swift/Win32 a little bit  - I want to make some classes `open`.
I first wanted to run the unit tests to make sure I don't break anything, but I struggled to find out how to do it. I'm used to programming on macOS and doing it on Windows is a little bit confusing to me. Anyways, after few hours of digging through Google and this repo I finally found the solution and I thought it would be great if it could be documented in the readme.
I am not sure if those instructions are missing something, but in my case this was enough.

Add an instruction for running unit tests

---

Sources/SwiftWin32/CG/Rect.swift

Correct a copy-paste error in the definition of `null`.

Rect: correct the representation of `Rect.null`

---

Sources/SwiftWin32/Menus and Shortcuts/MenuElement.swift

`MenuElement` should be an `open` class so that users may subclass the
`MenuElement` type for implementing custom accessors.

Menus and Shortcuts: open `MenuElement`

---

Sources/SwiftWin32/Menus and Shortcuts/Action.swift

`Action` should be an `open` class so that users may subclass it.  The
class should have all the expected properties at least stubbed.

Menus and Shortcuts: open Action for subclassing

---

Sources/SwiftWin32/Menus and Shortcuts/Action.swift
Sources/SwiftWin32/Views and Controls/Button.swift
Sources/SwiftWin32/Views and Controls/Control.swift
Tests/UICoreTests/ButtonTests.swift

This allows us to use the newer `Action` based handler to build up
interfaces.  It extends `Control` to invoke an `ActionHandler` rather
than work solely with the target-action pattern.

Button: add support for `Action` based handling

---

Examples/UICatalog/UICatalog.swift

Use the new Action based handler to remove an extension and a private
method.  This demonstrates more of the API surface and reduces the
amount of code.

UICatalog: simplify example code

---

Sources/SwiftWin32/Views and Controls/Button.swift

This adds the enumeration of the various styles of buttons that are
available by default.  This can be used to implement additional helper
constructors for `Button`.

Button: add `Button.ButtonType` enumeration

---

Sources/SwiftWin32/Views and Controls/Slider.swift

Add some documentation comments to the Slider implementation.  Take the
opportunity to clean up some of the text to fit better in 80-columns,
and make ignored results explicit.

Slider: documentation comments and formatting (NFC)

---

.github/workflows/coverage.yml

This sets up the initial workflow for getting code-coverage information
from the build.  Because we want to track the changes overtime, the
uploaded status should be based on the merged changes, though it would
be nice to get indication on how a change influences the coverage.

workflows: mock up a code-coverage workflow

---

.github/workflows/lint.yml

The use of compnerd/swift-format-linter-action avoids the need for the
`pull_request_target` workflow trigger as lint issues are reported via
the GitHub workflow events and does not require write access.

workflows: move linting to `pull_request`

---

.vscode/settings.json
.vscode/tasks.json

This adds a workspace configuration to the project to make it easier for
someone to get started.  It adds integration for building with SwiftPM
and ignores the build artifacts and vim swapfiles.

VSCode: add workspace configuration

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Event.swift

Adjust indentation for Event enumerations to reflect the Swift style.

Event: correct indentation for enum (NFC)

---

Sources/SwiftWin32/CMakeLists.txt

This has been removed from the SPM build, remove it from the CMake build
as well.

build: remove TBD validation workaround from CMake

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Event.swift

Repair the region specifier for `Event` to ensure that it does not get
mistaken for documentation.

Event: fix an invalid comment leader (NFC)

---

Sources/SwiftWin32/App and Environment/TraitCollection.swift

Fix indentation for enumerations in TraitCollection.  This fixes the
style to match the style as dictated by Swift.

App and Environment: adjust style (NFC)

---

Package.swift
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Support/WinSDK+UIExtensions.swift
Sources/SwiftWin32/Views and Controls/Stepper.swift
Tests/UICoreTests/StepperTests.swift
Tests/Utilities/Utilities.swift

Add a helper function to access the user data associated with a HWND and
convert it to a type.  This is generally useful and will be used
subsequently to implement more functionality.

UIExtensions: add `UserData` helper function

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Press.swift

This adds a definition of `Press`, excluding the `key` field which
requires additional types to be defined.

Touches, Presses, and Gestures: add `Press`

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Touch.swift

Adjust the incorrect indentation for `case` statements in the `enum`.

Touch: adjust indentation for Swift style (NFC)

---

Sources/SwiftWin32/Views and Controls/Switch.swift

The control subclass is currently unused, simply remove the unnecessary
subclassing until we find a need for it.

Views and Controls: remove unnecessary subclass

---

Sources/SwiftWin32UI/Framework Integration/UIApplicationDelegateAdaptor.swift

Add a definition of the `UIApplicationDelegateAdaptor` property wrapper.

Framework Integration: add `UIApplicationDelegateAdaptor`

---

Sources/SwiftWin32/View Controllers/ViewController.swift

Mark the fact that property is meant to be read-write more explicit.

UI: make it more explicit that the property is RW

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Touches, Presses, and Gestures/Event.swift
Tests/UICoreTests/EventTests.swift

This adds missing members to `Event`.  Additionally, extend the
designated initializer to ensure that we can easily subtype it as
appropriate.  Now that the type is well specified, mark it as `open` to
allow it to be derived by `open` types.

Touches, Presses, and Gestures: flesh out `Event`

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Press.swift
Tests/UICoreTests/PressTests.swift

This adds the missing interfaces in `Press`, extracts the subtypes into
extensions, and adds a conformance for equatable and hashable.  The
equality if currently based on pointer identity, though it is
questionable if the equality should be value based.  The hashable
conformance simply adds the members.
`Press` is also now `open` to allow derivations by `open` types.

Touches, Presses, and Gestures: flesh out `Press`

---

Sources/SwiftWin32/Touches, Presses, and Gestures/PressesEvent.swift
Tests/UICoreTests/PressesEventTests.swift

Add a definition for `PressesEvent` which is needed by `Responder`.

Touches, Presses, and Gestures: add `PressesEvent`

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Menus and Shortcuts/Menu.swift
Sources/SwiftWin32/Menus and Shortcuts/MenuElement.swift
Sources/SwiftWin32/Platform/Win32+Menu.swift

This extracts the menu logic out of the various files into a standalone
platform support structure to isolate the logic.

Menus and Shortcuts: split out the Win32 menu support

---

Sources/SwiftWin32/Menus and Shortcuts/Menu.swift
Sources/SwiftWin32/Touches, Presses, and Gestures/Press.swift

Make `Menu` conform to `Equatable` and `Hashable`.  This is required for
`Menu` to be used in an `OrderedSet`.  Technically, the type can inherit
from `NSObject`, which gives it an implicit `Equatable` and `Hashable`
conformance.  Since we do not pervasively use `NSObject`, we must
synthesize the conformance explicitly.
Tweak the comments for `Press`'s conformances so that we can find all of
them with a single pattern.

Menus and Shortcuts: add `Equatable` and `Hashable` conformances

---

Sources/SwiftWin32/Menus and Shortcuts/Menu.swift

Include the members in the hashing rather than the object identifier.

Menus and Shortcuts: tweak hashing

---

Sources/SwiftWin32/Menus and Shortcuts/Menu.swift
Sources/SwiftWin32/Platform/Win32+Menu.swift
Tests/UICoreTests/MenuBuilderTests.swift

This is meant to be the internal implementation for a Windows menu
system/builder interface.  When complete, this should be able to subsume
the current implementation of `Win32Menu` and `Win32MenuElement`.  This
implementation instead keeps everything in terms of the raw `Menu` type
for the duration of the builder's lifetime.  When the builder is
complete, we can take the description as provided by the fluent
MenuBuilder API and materialize the menu structure in a single pass.
This will avoid the unnecessary allocation of handles during the
construction.

Platform: start implementing a `MenuBuilder` for Win32

---

Sources/SwiftWin32/Views and Controls/View.swift

Use `window?.windowScene?.scene` rather than `window?.scene` to
determine the traits.

View and Controls: avoid a deprecation warning (NFC)

---

Sources/SwiftWin32/Windows and Screens/Window.swift
Tests/UICoreTests/ViewTests.swift

This starts adding some support for moving scenes on a Window.  The
motivation here was more for the testing than the need for the scene
organization.  This uncovered the fact that we do not handle the window
property on a view properly, resulting in it being improperly nil.

Windows and Screens: partially support scene movement

---

Sources/SwiftWin32/Menus and Shortcuts/MenuSystem.swift

Adjust the definition of `MenuSystem` to convert the class to `open`.

Menus and Shortcuts: open `MenuSystem`

---

Sources/SwiftWin32/Touches, Presses, and Gestures/Responder.swift

This mimics the UIKit's `UIResponder` API. These overloads will be wired to the `ViewController` to actually display the menus.
By default let's just pass the events to the next responder. The subclasses which need a custom menu will need to override these.

Menus and Shortcuts: add overloads for window menu construction

---

Sources/SwiftWin32/Menus and Shortcuts/Menu.swift

This corrects a typo in the identifier name.  The value is meaningless
in practical terms as the `ObjectIdentifier` is the identifier (that is,
it is used for pointer identity), but it is annoying.

Menus and Shortcuts: correct typo for identifier (NFC)

---

Sources/SwiftWin32/App Extensions/InputViewController.swift
Sources/SwiftWin32/Touches, Presses, and Gestures/Responder.swift

This completes the class interface declaration, though it remains
undefined largely.  Additionally, mark the class as `open` to allow
inheritance by other `open` classes to enable the classes to be extended
externally.

Responder: add missing interfaces, mark the class as open

---

Sources/SwiftWin32/Platform/Win32+Menu.swift
Sources/SwiftWin32/Views and Controls/View.swift

This was not completed, and more importantly, took over a name that is
meant to be used in subclasses.  This renames the `menu` item to
`hMenu`, and makes it a menu handle.  The construction of the menu needs
to be plumbed through, but this removes the old handling while the new
handling is implemented.

View and Controls: remove context menu handling

---

Sources/SwiftWin32/Platform/Win32+Menu.swift
Tests/UICoreTests/MenuBuilderTests.swift

This change teaches `_MenuBuilder` to build the window menus. It handles submenus & icons similarly to `Win32Menu`.

Menus and Shortcuts: make `_MenuBuilder` materialize the menus

---

Sources/SwiftWin32/Menus and Shortcuts/Menu.swift

This opens up the `Menu` type for derivation outside of the module.

Menus and Shortcuts: convert `Menu` to `open`

---

Sources/SwiftWin32/Platform/Win32+Menu.swift
Sources/SwiftWin32/Windows and Screens/Window.swift
Tests/UICoreTests/WindowTests.swift

This adds support for window-level menus, shown on the top of a window.
`_MenuBuilder` is used to construct the menus.

Menus and Shortcuts: support window menus

---

CMakeLists.txt
Sources/CMakeLists.txt

Static library support is experimentally supported on main, which this
project takes advantage of.  Be a bit more careful about enabling the
support to try to keep builds with 5.4.x working.
Fixes: #628

build: try to prevent use of static libraries on <5.5

---

Sources/SwiftWin32/Drawing/Color.swift
Tests/UICoreTests/ColorTests.swift

This adds the accessors for color information and associated tests.  The
accessors currently do not perform color space conversion.

Drawing: extend the Color interface to get color info

---

Sources/SwiftWin32/Views and Controls/Offset.swift
Tests/UICoreTests/OffsetTests.swift

Add a definition for `Offset` and associated tests.  This is needed to
start fleshing out dependencies for `SplitViewController`.

Views and Controls: add an implementation of `Offset`

---

Sources/SwiftWin32/Animation and Haptics/View Controller Transitions/ViewControllerTransitionCoordinatorContext.swift
Sources/SwiftWin32/Animation and Haptics/ViewControllerContextTransitioning.swift
Sources/SwiftWin32/CMakeLists.txt

Add the definition for the `ViewControllerContextTransitioning` protocol
which is needed the rest of the type hierarchy required for the
`ViewController` type.

Animation and Haptics: define `ViewControllerContextTransitioning`

---

Package.swift

Ensure that the CMake and SPM builds are at the same point.  If the user
does not initialize the submodules, we would fail to build as the
resolution would pick a different point for Swift/COM.

build: pin Swift/COM at the same point as the CMake build

---

Sources/SwiftWin32/CG/Vector.swift
Tests/CoreGraphicsTests/CoreGraphicsTests.swift
Tests/UICoreTests/CubicTimingParametersTests.swift
Tests/UICoreTests/SpringTimingParametersTests.swift

This member is meant to be public, but was accidentally internal.

CoreGraphics: make `Vector.zero` public

---

Sources/SwiftWin32/View Controllers/ViewController.swift

Add additional discussion on the various methods and properties for the
`ViewController` type.  This is primarily motivated by trying to correct
the default values for the type properties.

View Controllers: add additional documentation for `ViewController`

---

Sources/SwiftWin32/Views and Controls/BarButtonItem.swift
Sources/SwiftWin32/Views and Controls/BarButtonItemGroup.swift
Sources/SwiftWin32/Views and Controls/BarPositioning.swift
Tests/UICoreTests/BarButtonItemTests.swift

This adds the `BarButtonItem` type in order to flesh out the
`ViewController` interfaces in order to open the type.

Views and Controls: add `BarButtomItem`

---

Sources/SwiftWin32/Views and Controls/View.swift

Correct the hook-point `didMoveToWindow` in `View`.

Views and Control: correct a method name in `View`

---

Sources/SwiftWin32/App and Environment/TraitCollection.swift

Add some documentation comments for the enumeration and rename a few of
them to be more descriptive:
- pad: tablet
- mac: desktop
Add a new `headset` case for devices such as the HoloLens.

App and Environment: update `UserInterfaceIdiom`

---

Sources/SwiftWin32/App and Environment/TraitCollection.swift

Replace `.pad` with `.tablet`.  NFC

App and Environment: avoid a deprecation warning

---

Sources/SwiftWin32/Views and Controls/View.swift

Add the declarations for the subview layout operations.  These are
triggered through the `SplitViewController`.

Views and Control: add some extensions for layouts

---

Sources/SwiftWin32/App and Environment/TraitCollection.swift

Indicate the renaming via the availability attribute rather than the
custom message for a more homogeneous messaging.

App and Environment: use `renamed:` variant of availability

---

.github/workflows/documentation.yml

Although the interfaces here are not particularly exposed as part of the
SwiftWin32 interfaces, this adds a separate module for the purposes of
documentation hierarchy.  It makes it easier to locate the documentation
when needed.

actions: add an additional documentation module

---

Sources/SwiftWin32/Views and Controls/View.swift

This adds the definition for the `View.TintAdjustmentMode` enumeration
to enable extending the interface for `View`.

Views and Controls: define `View.TintAdjustmentMode`

---

CMakePresets.json

This adds a default configuration that is recommended as a preset:
- Release Build with Ninja, with `-sdk %SDKROOT%` as the Swift flags.
This should help make it get started with the CMake based build with
VSCode or any IDE which supports CMakePresets.

build: add a CMakePresets for the project

---

Package.swift
Sources/SwiftWin32/Support/Date+Extensions.swift
Tests/SupportTests/DateTests.swift

This adds some conversion helpers for `FILETIME` and `SYSTEMTIME`.
These are intended to help support adding accessors for the `DatePicker`
control.

Support: add some helpers for time conversion

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Views and Controls/DatePicker.swift
Tests/UICoreTests/DatePickerTests.swift

Add the `date` property and `setDate(_:animated:)` function to provide
access to the value selected by the `DatePicker` control.
Fixes: #677

DatePicker: add accessors for the `DatePicker`

---

Sources/SwiftWin32/Views and Controls/DatePicker.swift

Silence a warning about an unmutated `var` by changing it to `let`.

DatePicker: silence a warning (NFC)

---

Sources/SwiftWin32/App and Environment/Application.swift
Sources/SwiftWin32/App and Environment/TraitCollection.swift

This moves the source file used for the `ContentSizeCategory` extensible
enumeration.  It adds some missing interfaces as well.

App and Environment: shuffle & extend `ContentSizeCategory`

---

Examples/UICatalog/UICatalog.swift
Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Views and Controls/PickerView.swift

This adds a constrained implementation of PickerView.  It sketches out
the various pieces that are needed to get a working picker view.
Ideally, we would use the `CBS_OWNERDRAWVARIABLE` to render the views
individually sized, but that seems to cause an issue with the draw
operation, where the draw is never invoked for each item.  This
currently restricts us to equal sized views rather than variable sized
views.
The other important missing piece here is the lack of support for
multi-component pickers.  This should be possible to do in practice
since the backing widget tree is a ListBox and an Edit container.  We
should be able to render more complicated views accordingly.
~~An item that this work has uncovered is the lack of respect for
`sizeThatFits` involving a label.~~
Resolves: #425

PickerView: add an initial implementation of PickerView

---

Sources/SwiftWin32/Views and Controls/TextView.swift
Tests/UICoreTests/TextViewTests.swift

This would end up truncating when trying to be 32-bit clean.  Instead,
just drop the casts.

TextView: remove unnecessary casting

---

Sources/SwiftWin32/Views and Controls/Label.swift

`GetWindowTextW` is documented as:
```
If the function succeeds, the return value is the length, in characters,
of the copied string, not including the terminating null character.
```
Ensure that we properly account for the trailing null character.

Views and Control: correct `Label` content access

---

Tests/UICoreTests/TextViewTests.swift

We need to ensure that the richedit module is loaded before we attempt
to use the richedit based controls.  This is normally taken care of
during the application setup, but because the tests do not run as an
application, we need to handle this in the test harness setup.  The
tests should subsequently verify that the module was loaded.

tests: ensure that the setup succeeded when testing

---

Sources/SwiftWin32/Platform/WindowClass.swift

This class should not be extended as it is an internal implementation
detail.  Mark the class as `final`.

Platform: mark `WindowClass` as `final`

---

Sources/SwiftWin32UI/Views and Controls/Label.swift

This adds the `Label` interface as a placeholder for the type.

SwiftUI: add placeholder for `Label`.

---

azure-pipelines.yml

Since we explicitly download the latest modulemap from the Swift repository,
update for the restructuring that is in progress.

CI: adjust azure pipelines setup

---

Sources/SwiftWin32/Platform/Win32+PropertyWrappers.swift

Ensure that we allocate the space for the trailing nul terminator in the
string.  We would otherwise be off by one when converting the string.

Platform: account for nul terminator

---

cmake/Modules/SwiftSupport.cmake

While building the project with `cmake`, an unexpected error occurred in relation to my laptop CPU architecture. Currently, I'm running a Parallels VM of Windows 11 on a M1 Max MacBook Pro. As such, I discovered that the Apple Silicon `ARM64` architecture was not supported - possible use cases and scenarios include running windows on a Virtual Machine (VM), dual-boot or on Apple Bootcamp. Therefore, I have added the `ARM64 [x86_64]` CPU type under `.\cmake\Modules\SwiftSupport.cmake`. After trying and testing it out, it now works with support for M1/M2 Macs.
The original error occurred while running the suggested session line:
`cmake -B build -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS="-sdk %SDKROOT%" -G Ninja -S .`
This was the output at the end:
```
CMake …
```

Support for Apple Silicon ARM CPUs

---

.github/workflows/build.yml

This simply renders a pretty name for the branch when building to identify the current branch being buiilt.

GHA: name the jobs (NFC)

---

.github/workflows/build.yml

Introduce a 5.8 release train to the build matrix.

GHA: add a 5.8 build train

---

.github/workflows/build.yml
Sources/SwiftWin32/Platform/Error.swift

The buffer size for `_strerror` and `_wcserror` are fixed at 94 characters.  Use this to allocate the fixed size buffer and build the error message using `_wcserror_s` to avoid the warning as the allocation should be small enough to get stack promoted.

Platform: avoid warning from use of `_strerror_s`

---

Sources/SwiftWin32/View Controllers/ViewController.swift

If the hWnd does not have a window title, assume that there is no title and return `nil`.  Account for the trailing nul-terminator on the title when copying the text.

View Controller: account for no title condition

---

.github/workflows/lint.yml

Update the linting workflow to use the 5.8 release to gain the newer functionality and better stability.

GHA: update the lint workflow to 5.8

---

Sources/SwiftWin32/Windows and Screens/Window.swift

When the Window is assigned a `rootViewController`, we should trigger a `viewDidLoad` event.

Windows and Screens: trigger a `viewDidLoad` in `ViewController`

---

Sources/SwiftWin32/CMakeLists.txt
Sources/SwiftWin32/Views and Controls/Label.swift
Sources/SwiftWin32/Views and Controls/TextAlignment.swift
Sources/SwiftWin32/Views and Controls/TextField.swift
Tests/UICoreTests/LabelTests.swift

Add the missing `textAlignment` property for the partial cases which are trivial to map.  This allows for better control over the rendering of the text.

SwiftWin32: add `Label.textAlignment` property

---

Sources/SwiftWin32/Support/WindowsHandle+UIExtensions.swift

Sort the managed handles to make new ones easier to find.
Add a new managed handle type for brushes. This Windows type is used for painting a region.

Support: add a managed bursh

---

Sources/SwiftWin32/CG/Rect.swift
Sources/SwiftWin32/Views and Controls/View.swift

This refactors the DPI scaling for the rectangle to a function that we can use more broadly internally.  The broader availability prepares us for fixing higher DPI displays.

SwiftWin32: extract the `ScaleClient(rect:for:_)`

---

Sources/SwiftWin32/Views and Controls/View.swift

Generate a solid brush when we assign a background colour to a view. This will then be used to erase the background to a solid fill when rendering the view. This is sufficient in some cases but not in others. The application of the null brush should give us a transparent view but seems to not function properly.

Views and Controls: support background colours

---

Sources/SwiftWin32/Views and Controls/Label.swift

Scale the label size for the DPI.  This corrects the rendering of the label when the display is scaled to a value other than 100%.

Views and Controls: scale the label size

---

Package@swift-5.4.swift
Package@swift-5.5.swift
Package@swift-5.6.swift

Split up the package manifest to inline the features as per the toolchain version rather than doing the version configuration by preprocessing.

SPM: provide a version specific manifest

---

Sources/SwiftWin32/App and Environment/Device.swift

Hi @compnerd, before I jump to the PR I just wanted to say thanks for all the work you're putting into this project 😀
`GetComputerNameW` disregards the null terminator when returning the size of the buffer. This leads to the following error when using `Device.name`:
`Swift/CString.swift:284: Fatal error: input of decodeCString(_:as:repairingInvalidCodeUnits:) must be null-terminated`
Compensated the buffer size to account for the null terminator.

SwiftWin32: compensate for `GetComputerNameW`'s disregard of the null terminator

---

README.md

Add more information about compiling with cmake as mentioned in [#768 ](https://github.com/compnerd/swift-win32/issues/768#issuecomment-1783268566)

Update cmake section in readme with required env-vars

---

Package@swift-5.7.swift
Package@swift-5.8.swift
Sources/SwiftWin32/Platform/Win32+Menu.swift
Sources/SwiftWin32/Support/Logging.swift

Use the newly minted support for access control on imports (SE-0409) to clean up some newer warnings.

SwiftWin32: silence warning on recent development compilers

---

Sources/SwiftWin32/Support/String+UIExtensions.swift

Clean up the unused extension for `String` as work towards removing the UTF16 string extensions.

Support: remove extension that is unused

---

Sources/SwiftWin32/App and Environment/ApplicationMain.swift
Sources/SwiftWin32/Support/WinSDK+Extensions.swift

Enable the tab control behaviours for Common Controls to allow us to build out some of the tab view handling.

SwiftWin32: enable tab control in ComCtl32
