compnerd/swift-win32

- CMakeLists.txt
- add COBJMACROS  to force the C API instead of the C++ api
> forces the C API  in CMakeLists.txt

- Sources/UI/WindowClass.swift
- expose style and hbrBackground in the constructor
> Window Class Ctor changes

- Sources/CG/Rect.swift
- Sources/Support/Rect+UIExtensions.swift
- Sources/UI/View.swift
`Rect` is `{{dd},{dd}}`, a pair of `Point`, and `Size`.  Adjust the
definition and adjust usage accordingly.
> CG: correct definition of Rect

- Sources/CMakeLists.txt
- Sources/Support/WinSDK+Extensions.swift
- Sources/UI/Device.swift
This adds the `Device` type and adds the ability to get the device name
and OS information.
> UI: Add `Device` with a skeleton implementation

- Sources/CMakeLists.txt
- Sources/UI/Device.swift
- Sources/UI/TraitCollection.swift
Add the TraitCollection for collecting traits for the application.  This
will enable detecting dark mode vs light mode and to query the display
settings for font size.
> UI: add TraitCollection for collecting traits

- Sources/Application/Application.swift
Although these are not currently configured, add them so that when
appropriate, it is possible to wire them up.
> Application: add some launch keys

- Examples/CMakeLists.txt
- Examples/Calculator.exe.manifest
- Examples/Calculator.swift
This does the very basic integeral operations.  Floating point
operations needs to be added, as well as the ability to clear the state
and do percentage operations.
> Exmaples: add a demo calculator

- Sources/Application/ApplicationMain.swift
Adds a second hook to provide an out-of-band message filtering.
> Application: add Message Procedure Hook

- Sources/UI/View.swift
This ensures that we scale the frame for the window with the DPI for the
window upon creation.
> UI: adjust view rectangle for DPI

- Sources/UI/View.swift
This adjusts the handling of the `frame` property to preserve the user
specified values.  The frame is scaled at the time of re-parenting and
adjusted for overlapped windows if created with `CW_USEDEFAULT`.  This
removes the unnecessary computation on the construction of the view as
the frame is not adjusted for the DPI adjusted values.
> UI: preserve `frame` and scale as appropriate

- Sources/Application/ApplicationMain.swift
- Sources/Support/WinSDK+Extensions.swift
- Sources/UI/WindowClass.swift
Add support for RichEdit to Swift/Win32.  This will eventually be useful
for replacing the `TextView`.  It would also be useful for replacing
`TextField`.
> UI: Support RichEdit 5.0

- Sources/UI/View.swift
Use the newly minted functionality of setting the frame to resize the
window when reparenting.  This allows for the re-use of the logic rather
than duplicating it.  There is still room to improve the remapping of
the corrdinates when re-parenting but this seems to function
sufficiently for now.
Ensure that an overlapped window is never re-parented as that is
ill-defined.  Explicitly remove the `WS_POPUP` style when reparenting.
`SetParent` will not adjust the window style, we must explicitly remove
the `WS_POPUP` attribute (in case the window was previously parented by
the desktop window) and set the `WS_CHILD` attribute.  Reorder the
handling to update the style being invoking `SetWindowPos` to refresh
the frame after the adjusted window properties (`SetWindowLongPtr`).
> View: adjust the frame and reset when reparenting

- Sources/UI/Font.swift
Extract the font conversions for point to logical and logical to point
size conversion.
> UI: extract helpers for font size conversion

- Sources/UI/Font.swift
This adds some constructors to construct the system font in various
styles.
> UI: add constructors for system font access

- Sources/UI/Font.swift
This allows the construction of the desired font for different use cases
in applications.
> UI: add constructor for the preferred font

- Sources/UI/View.swift
This allows control over the Win32 Window's visibility.
> View: add support for `isHidden` property

- Examples/Calculator.swift
This fixes incorrect truncation of the value on repeated application.
> Calculator: fix `+/-` application

- Examples/Calculator.swift
Add an all clear button to the calculator.
> Calculator: default the input to `0`, add `AC`

- Sources/UI/View.swift
Restructure the window class and style storage to avoid the `style` and
`class` properties to allow use of those names.
> UI: restructure window class and style storage

- Examples/HelloSwift.swift
- Sources/CMakeLists.txt
- Sources/UI/Switch.swift
The Switch button type allows for an option to be selected or not.
> UI: introduce `Switch` view

- Sources/UI/View.swift
We would previously compute the frame of the top-level window
incorrectly: the window is created with `WS_VISIBLE` and so the
`GetWindowRect` would give the size of the non-client area and the drop
shadow.  Use `GetClientRect` and `ClientToScreen` to convert the window
frame to screen units.  Furthermore, this avoids the DPI virtualization
that is part of the `GetWindowRect`.
Reparent the subview earlier during the process.  This is important to
get the full state of the window correct.
> UI: fix a few window sizing issues

- Sources/UI/Device.swift
Add the ability to get the status of the battery from `Device`.
> UI: add support to query battery status

- Examples/UICatalog/UICatalog.swift
- Sources/UI/Button.swift
- Sources/UI/DatePicker.swift
- Sources/UI/Label.swift
- Sources/UI/ProgressView.swift
- Sources/UI/Slider.swift
- Sources/UI/Switch.swift
- Sources/UI/TextField.swift
- Sources/UI/TextView.swift
- Sources/UI/View.swift
Setup the battery level notification.  We can now report the battery
level changes to the application.
> UI: add support for battery level notification

- Sources/UI/Control.swift
This is meant to be used to add event handling for controls like
buttons.
> UI: add `Control.Event` type

- Examples/UICatalog/UICatalog.swift
With the improvements to the control rendering, the location for the
control now are logical.  Update the position information to be more
consistent to render a nicer view.
> UICatalog: improve the control layout

- Sources/UI/Control.swift
Generalise the event callable to be type-constrained to the control type
ensuring that the sender is of the same type rather than restricting to
just `Button`.
> UI: loosen restriction on control target binding

- Sources/UI/Stepper.swift
Add support for actually controlling the minimum, maximum range, and
whether the control wraps.  Additionally enable altering the step value
for the control.
> UI: implement a number of control properties

- Examples/Calculator/Calculator.swift
This migrates the Calculator demo to the action target model for
responding to the button presses.  This removes the vast majority of the
Win32 specific knowledge from the demo application.  The last piece that
remains at this point is the `CW_USEDEFAULT` used to place the window
where the window manager believes that the Window should be placed.
> Calculator: adopt target action model for button handling

- Sources/CMakeLists.txt
- Sources/UI/AnimationCurve.swift
- Sources/UI/ContentContainer.swift
- Sources/UI/ViewController.swift
- Sources/UI/ViewControllerTransitionCoordinator.swift
- Sources/UI/ViewControllerTransitionCoordinatorContext.swift
Define `ContentContainer` protocol and dependencies and make
`ViewController` conform to it.
> UI: make `ViewController` a `ContentContainer`

- Sources/UI/Font.swift
Group together the operations to make them easier to follow.
> UI: group font operations (NFC)

- Examples/Calculator/Calculator.swift
Don't make the sender optional, make the display private now that the
state does not need access to it.
> Calculator: clean up some of the example code

- Sources/UI/Font.swift
Add accessors for the preferred font sizes.
> UI: add font size accessors

- Sources/UI/TraitCollection.swift
Adjust the default value for the `displayScale` default.  Add the active
interface style trait.
> UI: update trait collections

- Examples/UICatalog/UICatalog.swift
- Sources/CMakeLists.txt
- Sources/UI/TextField.swift
- Sources/UI/TextInputTraits.swift
Add control over the TextField to enable secure entry mode.  This allows
for the construction of a password field that can accept obscured input.
This is controlled via the `TextInputTraits` protocol.
> UI: add support for secure text entries

- Sources/UI/Device.swift
Add support to check if the device is in portrait or landscape mode.
> UI: add support to determine the current orientation

- Sources/UI/Font.swift
This adds additional accessors and constructors for information about
fonts.
> UI: extend `Font` properties

- Sources/UI/Switch.swift
Enable control over the `Switch` control.
> UI: add `isOn` and `setOn(_:animated:)` to `Switch`

- Sources/UI/TraitCollection.swift
Populate the `horizontalSizeClass` and `verticalSizeClass` based on the
device orientation.  The `displayScale` uses the primary display's scale
factor.  The `displayGamut` is currently assumed to be `sRGB` even
though we cannot currently identify it properly.
> UI: populate more of `TraitCollection`

- Sources/UI/Font.swift
Define the typography information to dynamically size the font for the
traits.
> UI: add typography information to font

- Examples/CMakeLists.txt
- Examples/HelloWorld/CMakeLists.txt
- Examples/HelloWorld/HelloWorld.swift
- Sources/UI/Screen.swift
This is the simplest possible application that simply creates a basic
640x480 window which is placed by the window manager on the screen as
it deems best.
> Examples: add an empty "Hello World" example

- Sources/Application/ApplicationDelegate.swift
Add some more entry points for application delegate callbacks that
aren't wired up yet.  Add some notification names for
`ApplicationDelegate`.
> Application: flesh out `ApplicationDelegate`

- Sources/UI/View.swift
This adds a variable to encapsulate most of the Win32 specific window
details (window style and window class).  Ideally, the `hWnd` for the
View would also be encapsulated into the `win32` variable freeing up any
overlap between the rest of the API and making it easier to explicitly
delineate the Win32 specifics allowing the possibility of trying to
re-use some of the application life cycle (and view controller handling
in the future) with a different backend (e.g. GTK+).
> UI: namespace `window` further into a variable (NFCI)

- Sources/Application/Application.swift
- Sources/Application/ApplicationDelegate.swift
- Sources/Application/_TriviallyConstructible.swift
- Sources/CMakeLists.txt
- Sources/UI/Responder.swift
- Sources/UI/View.swift
This will enable the view hierarchy to construct a responder chain,
enabling events to be handled down the view hierarchy.
> UI: add `Responder` for setting up a responder chain

- Sources/Application/ApplicationDelegate.swift
- Sources/CMakeLists.txt
- Sources/UI/Scene.swift
- Sources/UI/SceneConfiguration.swift
- Sources/UI/SceneDelegate.swift
- Sources/UI/SceneSession.swift
- Sources/UI/SceneSizeRestrictions.swift
- Sources/UI/WindowScene.swift
This sets up the initial approach to scene based handling.  This should
allow rendering with multi-interface devices like the Microsoft Surface
Duo.
> UI: start adding a scene based API

- Sources/Application/Application.swift
- Sources/Application/ApplicationMain.swift
- Sources/Application/Information.swift
- Sources/CMakeLists.txt
This adds a decoder for Info.plist to configure some attributes of the
application.
> Application: add support for processing an Info.plist

- Sources/Application/ApplicationMain.swift
This is a bit more verbose but allows for 80-column code.
> Application: reflow some text (NFC)

- Sources/UI/Window.swift
This PR adds `isMinimizable` & `isMaximizable` properties to the `Window` class.
> UI: allow disabling minimize/maximize buttons

- Examples/UICatalog/UICatalog.swift
- Sources/CMakeLists.txt
- Sources/Support/IndexPath+UIExtensions.swift
- Sources/UI/TableView.swift
- Sources/UI/TableViewCell.swift
- Sources/UI/TableViewDataSource.swift
Add a TableView control to the supported controls.  This allows
rendering a series of cells which can be scrolled through.  This
composite control will enable more rich UIs to be built.
> UI: introduce TableView

- Sources/UI/Stepper.swift
- Sources/UI/TableView.swift
Both the stepper and tableview use a proxy to handle notification
events.  This ensures that we have similar comments around the area and
renames the proxies to a more grammatically correct form.
> UI: homogenise the messenger proxy naming and comments

- Sources/Application/ApplicationMain.swift
- Sources/Support/WinSDK+Extensions.swift
Same as https://github.com/compnerd/swift-win32/pull/179 with fixed Double to DWORD conversion
> Improve Application main loop (fixed)

- Sources/Application/ApplicationMain.swift
Clean up the comments to be complete, grammatically correct sentences.
Simplify the logic for the main loop.
> Application: clean up comments, simplify logic (NFCI)

- Sources/Application/Application.swift
- Sources/Application/ApplicationDelegate.swift
- Sources/UI/TableViewCell.swift
Simply add some additional doc comments to the delegate methods.
> Application: add some doc-comments (NFC)

- Sources/UI/View.swift
Inform the previous parent and the view that the view is being adopted
by a new parent.
> UI: add more view observation hooks

- Sources/UI/View.swift
Add a property to `View` to control whether the view responds to window
events.
> UI: add `isUserInteractionEnabled` to `View`

- Sources/CMakeLists.txt
- Sources/UI/ContentSizeCategoryAdjusting.swift
- Sources/UI/Label.swift
- Sources/UI/TextField.swift
- Sources/UI/TextView.swift
This protocol enables the UI controls to automatically adjust when the
content size category changes.
> UI: introduce the `ContentSizeCategoryAdjusting` protocol

- Sources/UI/ViewController.swift
This lays out some of the basics for view management within the
ViewController.  The missing piece is the presentation of the view
associated with a view controller.
> UI: improve view management of ViewController

- Sources/Application/Application.swift
- Sources/Application/ApplicationMain.swift
- Sources/UI/Window.swift
- Sources/UI/WindowScene.swift
Start extending Window to integrate the scene model for the Window
management.
> UI: add Window notifications, extend WindowScene

- Sources/Application/ApplicationDelegate.swift
- Sources/UI/CoordinateSpace.swift
- Sources/UI/WindowSceneDelegate.swift
This defines the `WindowSceneDelegate` protocol to enable the
application to responding to the window scene.
> UI: add `WindowSceneDelegate`

- Sources/Application/Application.swift
This addresses the TODO to deserialise the information from the
Info.plist in the bundle.
> Application: respect Info.plist in `supportsMultipleScenes`

- Sources/UI/Window.swift
This adds a new designated initializer for `Window` to create it for a
given scene.  This grants control over the window resizing to the
application.
> UI: add `init(windowScene:)` constructor to `Window`

- Examples/HelloWorld/CMakeLists.txt
- Examples/HelloWorld/HelloWorld.swift
- Examples/HelloWorld/Info.plist
Migrate the empty program skeleton to a scene based window management
style that should be preferred.
> HelloWorld: adopt scene based management

- Sources/UI/SceneSizeRestrictions.swift
Default the window size restriction to 768x768.
> UI: adjust the default window size

- Package.swift
Introduce a dependency on compnerd/cassowary which will be useful to
implement layout constraint solving.
> build: add a dependency on the cassowary package

- Sources/AutoLayout/LayoutPriority.swift
In order to support constraint based UI development, add a
`LayoutPriority` type which will enable building constraints with
different priorities.
> AutoLayout: introduce `LayoutPriority`

- .gitignore
Explicitly ignore this file while in development
> add Package.resolved to .gitignore

- Sources/UI/BezierPath.swift
- Sources/UI/ContextMenuConfiguration.swift
- Sources/UI/ContextMenuInteraction.swift
- Sources/UI/ContextMenuInteractionAnimating.swift
- Sources/UI/ContextMenuInteractionCommitAnimating.swift
- Sources/UI/ContextMenuInteractionDelegate.swift
- Sources/UI/Image.swift
- Sources/UI/Menu.swift
- Sources/UI/MenuElement.swift
- Sources/UI/PreviewParameters.swift
- Sources/UI/PreviewTarget.swift
- Sources/UI/TargetedPreview.swift
This starts implementing the context menu related interfaces required
for the application to control the context menu.
> UI: add context menu interaction related types

- Sources/AutoLayout/LayoutAnchor.swift
- Sources/AutoLayout/LayoutConstraint.swift
- Sources/AutoLayout/LayoutDimension.swift
- Sources/AutoLayout/LayoutGuide.swift
- Sources/AutoLayout/LayoutPriority.swift
- Sources/AutoLayout/LayoutSupport.swift
- Sources/AutoLayout/LayoutXAxisAnchor.swift
- Sources/AutoLayout/LayoutYAxisAnchor.swift
Add some interfaces to work with the constrains on a View. This is still
largely incomplete and non-functional.  However, it lays out most of the
interfaces.
> UI: flesh out more of the AutoLayout interfaces

- Sources/SwiftWin32/AutoLayout/LayoutConstraint.swift
- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/UI/View.swift
Add some constructors for anchors for `View`.
> UI: add some anchor constructors to View

- Sources/SwiftWin32/UI/View.swift
Add the ability to tag and search views by the tags.  Although this is
not a great implementation, it is sufficient to use in a demo context.
> UI: basic implementation for view tagging

- Examples/Calculator/Calculator.swift
- Use `forEach` instead of `map` for more efficient handling of the
buttons.
- Use a variable initializer to demonstrate more advanced initialisation
techniques.
- Avoid an unnecessary forced unwrap, using a guard and `fatalError`
instead.
> Calculator: minor cleanups

- README.md
Add notes on the known limitations with SPM and explain the scenarios
where SPM is required.
> docs: expand on SPM build instructions

- Sources/SwiftWin32/UI/ContentContainer.swift
Add some doc comments to the interface (NFC).
> UI: add some documentation for `ContentContainer`

- Sources/SwiftWin32/UI/Window.swift
Stylistic change for the constants and add some doc-comments.
> UI: convert window level constants to computed vars

- Sources/SwiftWin32/UI/Image.swift
This allows us to load an image from a file and convert it to a form
that we can render to a `HBITMAP` enabling us to use this to render it
to a GDI context (Window).
> UI: add `Image` type

- Sources/SwiftWin32/UI/Image.swift
Add the ability to query the image size which is needed to render the
image to a view.
> UI: add some documentation and image size accessors

- Sources/SwiftWin32/UI/Scene.swift
Add more notification points for `Scene` which will be used as the
`Scene` API is fleshed out further.
> UI: add more notification events to `Scene`

- Sources/SwiftWin32/UI/View.swift
Update the window style update ordering around the `SetParent`.  This
corrects the ordering as per MSDN.
> UI: reorder window style setting

- Sources/SwiftWin32/UI/View.swift
This reduces the storage requirements on `Window`, removing the `style`
storage on `Window` since there is already the storage for that in
Window.  This cleans up the unnecessary workaround for a tuple of a
single entry.
Fixes: #220
> UI: remove style storage on `Window`

- Sources/SwiftWin32/Platform/OrientationSensor.swift
Use the Windows Sensors API to monitor the system orientation to allow
for notification on orientation changes.
> Platform: sketch out an orientation monitor

- Sources/SwiftWin32/UI/MenuElement.swift
Extracted from https://github.com/compnerd/swift-win32/pull/246
> UI: tweak `MenuElement` public interface

- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/UI/Interaction.swift
This is a basic protocol to define interactions with views.
> UI: introduce `Interaction` protocol

- Sources/SwiftUIWin32/ViewBuilder.swift
The `ViewBuilder` constructor here is trivial enough to just implement.
> SwiftUIWin32: implement trivial constructor

- Sources/CMakeLists.txt
- Sources/SwiftWin32UI/CMakeLists.txt
Ensure that we build this as part of the CMake based build as well.
> build: add SwiftWin32UI to the CMake based build

- Sources/SwiftWin32/CMakeLists.txt
Add missing file to the file list in the build system.
> build: add missing source file to source list

- Sources/SwiftWin32/CMakeLists.txt
Add additional source files that were being built with the SPM build but
not the CMake build.
> build: add more missing sources to the build file list

- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/UI/Action.swift
- Sources/SwiftWin32/UI/Command.swift
- Sources/SwiftWin32/UI/MenuBuilder.swift
- Sources/SwiftWin32/UI/MenuElement.swift
- Sources/SwiftWin32/UI/MenuSystem.swift
This is meant to support building the "system" menu (application menu)
in applications.
> UI: add skeleton for `MenuBuilder`

- Sources/SwiftWin32/UI/View.swift
Reorganise some regions within the file.
> UI: reorder some regions in View (NFC)

- Sources/SwiftWin32/UI/ContextMenuConfiguration.swift
- Sources/SwiftWin32/UI/View.swift
Improve some documentation and anchors for `ContextMenuConfiguration`.
> UI: improve `ContextMenuConfiguration` documentation

- Examples/UICatalog/UICatalog.swift
Tweak the height of the `TextField`s to make the text field more even.
> UICatalog: tweak layout further

- Sources/SwiftWin32/CA/Transform3D.swift
- Sources/SwiftWin32/CMakeLists.txt
Add a matrix representation of a transform.
> CA: add `Transform3D` type

- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/UI/TableViewDelegate.swift
- Sources/SwiftWin32/UI/TableViewFocusUpdateContext.swift
Add a declaration of the `TableViewDelegate` protocol.
> UI: add `TableViewDelegate` definition

- Sources/SwiftWin32/Windows and Screens/Window.swift
Sort the handled events in lexicographical ordering.
> UI: swap order of events (NFC)

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add some methods which will allow handling of event notification to
`ViewController` and its derivatives.
> UI: add view change handlers to `ViewController`

- Sources/SwiftWin32/Views and Controls/DirectionalEdgeInsets.swift
Add stubs to define the directional edge insets.
> Views and Controls: add `DirectionalEdgeInsets`

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add a definition of `RectEdge` to start handling layout better.
> View Controllers: add definition of `RectEdge`

- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/View Controllers/ViewController.swift
Further extend the `ViewController` interface for layout related
interfaces.  This is largely a stub which can be expanded upon
subsequently.
> UI: add placeholders for more of `ViewController`

- Sources/SwiftWin32/AutoLayout/LayoutAnchor.swift
- Sources/SwiftWin32/AutoLayout/LayoutConstraint.swift
- Sources/SwiftWin32/AutoLayout/LayoutDimension.swift
- Sources/SwiftWin32/AutoLayout/LayoutGuide.swift
- Sources/SwiftWin32/AutoLayout/LayoutXAxisAnchor.swift
- Sources/SwiftWin32/AutoLayout/LayoutYAxisAnchor.swift
Adjust the layout guide constructors to make more sense.
> AutoLayout: improve the factory methods for `LayoutGuide`

- .github/workflows/windows.yml
- azure-pipelines.yml
Update to `main` branch in the CI configuration.
> CI: switch default branch to `main`

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add additional interfaces to `ViewController`.
> View Controllers: extend the interfaces of `ViewController`

- Sources/SwiftWin32/Menus and Shortcuts/MenuElement.swift
- Sources/SwiftWin32/Views and Controls/ImageView.swift
This PR adds the support for icons displayed in context menu items, on the left side from the item title.
> UI: support icons in menu items

- Sources/SwiftWin32/Images and PDF/Image.swift
- Sources/SwiftWin32/Platform/OrientationSensor.swift
Now that Swift/COM supports proper memory management, remove the TODO as
this is taken care of.
> SwiftWin32: update Swift/COM usage for memory management

- Sources/SwiftWin32/App and Environment/Application.swift
- Sources/SwiftWin32/Touches, Presses, and Gestures/Responder.swift
- Allows defining appliction subclasses
- Required for using NSPrincipalClass
> Application and Responder are changed to open

- Sources/SwiftWin32/Application/Information.swift
- As in swift doc: https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html
> Added indentations in Information.swift enums

- Sources/SwiftWin32/Application/ApplicationMain.swift
Update the documentation be more grammatically correct and precise.
Reflow some text for 80-columns.
> Application: tweak comments and reflow some text (NFC)

- Sources/SwiftWin32/Views and Controls/Stepper.swift
The stepper minimum must always be less than or equal to the maximum
value.  Altering one which would violate the invariant results in both
being modified to the new value.  Ensure that this invariant always
holds.
> UI: add documentation for `Stepper` and some invariant validation

- Sources/SwiftWin32/Views and Controls/Switch.swift
Add some documentation comments to the `Swift` interfaces.
> UI: improve some documentation around `Switch`

- Tests/AutoLayoutTests/AutoLayoutTests.swift
Add some test cases for the `LayoutConstraint` interfaces.
> tests: add some minor trivial tests

- Sources/SwiftWin32/Views and Controls/View.swift
This may not be a complete and correct implementation, but is a starting
point.
> UI: add `View.remoteInteraction(_:)`

- Sources/SwiftWin32/Appearance Customization/Configurations/BackgroundConfiguration.swift
- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/Views and Controls/VisualEffect.swift
Add a definition for `BackgroundConfiguration` and the supporting
`VisualEffect` base type for the appearance effects.
> Appearance Customization: add definition of `BackgroundConfiguration`

- Sources/SwiftWin32/Appearance Customization/Configurations/ContentConfiguration.swift
- Sources/SwiftWin32/Appearance Customization/Configurations/ContentView.swift
Add a definition of the `ContentConfiguration` protocol.
> Appearance and Customization: add `ContentConfiguration`

- Sources/SwiftWin32/Text Storage/ParagraphStyle.swift
This adds the enumeration which is needed for ListContentConfiguration
and the header and footer cells in a table view.
> Text Storage: add LineMode

- Sources/SwiftWin32/Views and Controls/Table Views/TableViewHeaderFooterView.swift
- Sources/SwiftWin32/Views and Controls/View.swift
Add a definition of `TableViewHeaderFooterView` and the necessary
supporting changes (`ParagraphStyle` and `View.backgroundColor`).
> Views and Controls: add `TableViewHeaderFooterView`

- Sources/SwiftWin32/Views and Controls/View.swift
Simply re-order the properties related to the visual appearance to after
the construction.  NFC.
> View: reorder some properties

- Sources/SwiftWin32/Views and Controls/View.swift
Add additional interfaces to interact with the view hierarchy, adding
and removing views at various positions.  In particular, the ancestry
management is required for autolayout handling.
> View: improve view hierarchy management

- Sources/SwiftWin32/Views and Controls/Label.swift
- Sources/SwiftWin32/Views and Controls/View.swift
Further simplify the construction of the `Label` type.  We use the
window constructor to set the style and the parent on the instead of
applying them manually after the construction.  We can also avoid
computing the size of the window and instead use the size of the parent
window itself.  In theory, we could go further - the public API does not
permit the constructing the window parented, so we can rely on the
re-parenting to trigger the resizing, allowing the property observer to
trigger the resizing.
> Views and Controls: simplify `Label` construction

- Sources/SwiftWin32/Views and Controls/Stepper.swift
Indeed, it works better by switching the params :)
> Fix Stepper.value setter

- Sources/SwiftWin32/Views and Controls/Label.swift
Add a partial implementation for `sizeThatFits(_:)` for `Label`.  This
computes the extent of the rendered text in the currently specified
font.  This is missing support for frame margins and padding which
should be used to actually increase the size that fits, however, those
properties are not yet available on the type, making it not possible to
accommodate them in the current state.
The biggest missing piece here is support for multi-line titles and
support for attributed strings which are currently unsupported in the
implementation as well.
> Label: partially implement `sizeThatFits(_:)`

- Sources/SwiftWin32/Views and Controls/View.swift
This adds the `directionalLayoutMargins` property to the `View` type.
Additionally, wire up the property change notification.
> View: add content margin properties

- Sources/SwiftWin32/Appearance Customization/Appearance.swift
- Sources/SwiftWin32/Appearance Customization/AppearanceContainer.swift
Add the `Appearance` protocol definition.
> Appearance Customization: add `Appearance` protocol

- Sources/SwiftWin32/App and Environment/Application.swift
- Sources/SwiftWin32/App and Environment/TraitCollection.swift
Add some additional documentation to the types.  No functional change.
> App and Environment: add some more documentation (NFC)

- Sources/SwiftWin32/CG/AffineTransform.swift
This adds some documentation comments to `AffineTransform` (NFC).
> CG: Add some documentation to `AffineTransform`

- Package.swift
- Tests/CoreGraphicsTests/CoreGraphicsTests.swift
- Tests/main.swift
This adds some additional test coverage for the AffineTransform type.
> Tests: add some basic test coverage for `AffineTransform`

- .github/workflows/windows.yml
Add support for linting via swift-format for the Swift code.
> CI: integrate linter into the CI pipeline

- Sources/SwiftWin32/Touches, Presses, and Gestures/GestureRecognizer.swift
Restructure the code layout slightly to improve readability.  NFC.
> GestureRecognizer: extract GestureRecognizer.State (NFC)

- Sources/SwiftWin32/Support/Point+UIExtensions.swift
This adds support for adding and subtracting points.  The operation is
defined as if `Point` were the vector formed by the point and the
origin.  This gives it the normal mathematical semantics of point-wise
addition and subtraction on a 2D plane.
> Support: add some helpers to deal with point operations

- Sources/SwiftWin32/Touches, Presses, and Gestures/GestureRecognizer.swift
Add a few additional fields for tracking the recognizer state and the
associated view.
> GestureRecognizer: add some additional fields

- Sources/SwiftWin32/CG/Rect.swift
Simple change to fix midpoints on Rect.
> Fix midpoint calculations on Rect

- Sources/SwiftWin32/CG/Rect.swift
- Tests/CoreGraphicsTests/CoreGraphicsTests.swift
This should fix the affine transform operation on Rect.
> Fix applying() function on Rect

- Sources/SwiftWin32/CG/Rect.swift
This adjusts the declaration order and adds some documentation comments
for the `Rect` type.
> Rect: add some documentation comments (NFC)

- Sources/SwiftWin32/Support/Rect+UIExtensions.swift
Adding helper functions to `Rect`
> Add Rect center computed property

- Sources/SwiftWin32/CG/Rect.swift
Add some additional useful properties to `Rect`.  This will be used to
simplify some of logic to transform a rectangle.
> Rect: add some additional computed properties

- Sources/SwiftWin32/CG/Point.swift
Add some missing documentation comments and section markers for `Point`.
> Point: add some documentation comments (NFC)

- Sources/SwiftWin32/CG/Size.swift
Add some documentation comments and region markers to Size.
> Size: add some documentation comments (NFC)

- .github/workflows/build.yml
Rename the "windows" action to "build".
> Update and rename windows.yml to build.yml

- Sources/SwiftWin32/CG/Rect.swift
- Tests/CoreGraphicsTests/CoreGraphicsTests.swift
A simple test showing the operator at work is also included..
> Rework == operator on Rect to take standardization into account

- Sources/SwiftWin32/CG/Rect.swift
- Tests/CoreGraphicsTests/CoreGraphicsTests.swift
Add `Rect.union` and associated tests.
> Rect: add `union` operation

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add the hooks for subclasses to get notifications on containment
changes.
> View Controllers: add containment callbacks to `ViewController`

- Sources/SwiftWin32/Text Display and Fonts/Font.swift
This is a purely aesthetic change to make the style consistent with the
rest of the repository.
> Font: convert stored properties to getters

- Sources/SwiftWin32/Text Display and Fonts/Font.swift
This adds some doc comments for `Font.Weight` and `Font.TextStyle`.
> Font: add some documentation comments to Font

- .swift-format
This adds a .swift-format to tweak some of the default behaviours of
swift-format.  Although it isn't exactly the style used by this project,
it brings it closer.
> swift-format: add a .swift-format file

- Sources/SwiftWin32/View Controllers/ViewController.swift
Clean up some documentation comments from the linter.
> View Controllers: add some documentation comments

- Examples/Calculator/Calculator.swift
Migrate more operations to `NSDecimalNumber` which simplifies the math
handling.  It also simplifies the localization of the values.
> Calculator: use `NSDecimalNumber`

- Sources/SwiftWin32/Menus and Shortcuts/MenuElement.swift
Update documentation and style for `MenuElement`.
> Menus and Shortcuts: stylistic changes for `MenuElement`

- Sources/SwiftWin32/Views and Controls/Control.swift
Filter the triggering events first then invoke the handlers.  This is
slightly slower than doing it interspersed and may take a little more
memory (which can be handled by using `lazy`), but makes it easier to
reason about.  It hoists the event list out as Action bindings result
in a third use.
> Control: functional handling for event triggering

- Sources/SwiftWin32/Views and Controls/Button.swift
Add some documentation comments and an assertion for Button.
> Button: add some documentation comments

- Sources/SwiftWin32UI/App Structure and Behaviour/App.swift
- Sources/SwiftWin32UI/App Structure and Behaviour/Scene.swift
- Sources/SwiftWin32UI/App Structure and Behaviour/WindowGroup.swift
- Sources/SwiftWin32UI/CMakeLists.txt
Move some of the essential types into a new location.
> SwiftUI: reorganize a few files (NFC)

- .github/workflows/documentation.yml
- .github/workflows/lint.yml
This converts the documentation CD pipeline to use a matrix strategy to
allow a single configuration point.  This also converts the lint CI
pipeline to the same mechanism.
> workflows: use matrix strategy to configure Swift

- .github/actions/install-swift/action.yml
- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/lint.yml
This adds an adhoc action to handle the installation of Swift on
Windows.  This reduces the duplication of the process and can simplify
creation and updating of the installation process.
> workflows: extract Swift installation into an action

- .vscode/tasks.json
This allows the test tasks to properly execute.  Reflow the text as per
VSCode's preference (mostly).
> VSCode: tweak the tasks for testing, style

- .github/codecov.yml
This should improve the reporting on PRs.
> codecov: enable status updates on PRs

- Sources/SwiftWin32/App and Environment/Scenes/SceneSession.swift
Add some documentation comments and fix some regional anchors.
> App and Environment: update some comments (NFC)

- Sources/SwiftWin32/Windows and Screens/Window.swift
Add some documentation comments, add a few missing properties, and merge
an extraneous extension into the body.
> Windows and Scenes: improvements to Window

- Sources/SwiftWin32/Views and Controls/Switch.swift
Adjust the indentation to match Swift style.
> Views and Controls: adjust indentation (NFC)

- .gitattributes
- .gitmodules
- CMakeLists.txt
- Package.swift
- Sources/SwiftWin32/CMakeLists.txt
This adds a dependency on SwiftCollections so that we can use
OrderedCollections.
> build: add a dependency on SwiftCollections

- Sources/SwiftWin32/Windows and Screens/AlertAction.swift
- Sources/SwiftWin32/Windows and Screens/AlertController.swift
Add additional documentation for the members of these types.
> UI: add docs to `AlertAction`, `AlertController`

- Sources/SwiftWin32/Menus and Shortcuts/ContextMenuInteraction.swift
Correct indentation, add a missing documentation comment, minor
whitespace changes for text flow styling.
> Menus and Shortcuts: stylistic changes (NFC)

- Tests/UICoreTests/ResponderTests.swift
Validate the default properties in a `Responder`.
> Tests: add some basic tests for `Responder`

- Sources/SwiftWin32/Drawing/Color.swift
Add the `Color(dynamicProvider:)` constructor for `Color` and update the
various instances to use the new constructor to provide the dynamically
adjusting color.  The conversion to `COLORREF` will take the current
trait, which preserves the status quo behaviour, but enables future
enhancements to dynamically adjust to the traits for the rendering view.
Take the opportunity to add some additional documentation for the
various static members.
> Drawing: add new constructor for `Color`

- Sources/SwiftWin32/CMakeLists.txt
Somehow this was missed in CI.  Repair the build.
> build: repair the CMake based build

- Sources/SwiftWin32/App and Environment/ApplicationDelegate.swift
Add missing documentation and merge the notification names into the
appropriate extensions.  Increase coverage of expected notification
names.
> App and Environment: stylistic changes for ApplicationDelegate

- Sources/SwiftWin32/App and Environment/Application.swift
- Sources/SwiftWin32/View Controllers/ViewController.swift
- Sources/SwiftWin32/Views and Controls/View.swift
- Sources/SwiftWin32/Windows and Screens/Window.swift
This improves the responder hierarchy handling to be more correct.  One
of the largest changes occurs in the `ViewController` type which gains
more of its interfaces.  These are needed for presenting a view
controller and to have the parent-child relationship for the view
controllers.  These impact the view hierarchy and thus must be present.
> Responder: improve the responder hierarchy configuration

- Sources/SwiftWin32/App and Environment/Application.swift
Add some additional regional markers and add some missing documentation
comments.
> App and Environment: add more regional markers, doc comments

- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/ViewAnimating.swift
Add the `ViewAnimationPosition` enumeration for implementing
`ViewImplicitlyAnimating`.
> Animation and Haptics: add `ViewAnimatingPosition`

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add some documentation comments for `ModalTransitionStyle`.
> ViewController: add some additional documentation (NFC)

- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/CubicTimingParameters.swift
- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/SpringTimingParameters.swift
- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/TimingCurveProvider.swift
- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/ViewAnimating.swift
- Sources/SwiftWin32/Animation and Haptics/Property-Based Animations/ViewImplicitlyAnimating.swift
- Sources/SwiftWin32/Animation and Haptics/View Controller Transitions/ViewControllerAnimatedTransitioning.swift
- Sources/SwiftWin32/Animation and Haptics/View Controller Transitions/ViewControllerInteractiveTransitioning.swift
- Sources/SwiftWin32/Animation and Haptics/View Controller Transitions/ViewControllerTransitioningDelegate.swift
- Tests/UICoreTests/CubicTimingParametersTests.swift
- Tests/UICoreTests/SpringTimingParametersTests.swift
This fleshes out the protocols required for the `ViewController` class
interfaces.
> Animation and Haptics: add various ViewController animation protocols

- Sources/SwiftWin32/App and Environment/TraitCollection.swift
Add some documentation comments and add some additional interfaces for
`TraitCollection`.
> App and Environment: improve `TraitCollection`

- Sources/SwiftWin32/App and Environment/TraitEnvironment.swift
Add some doc-comments for `TraitEnvironment`.
> App and Environment: `TraitEnvironment` documentation comments

- Sources/SwiftWin32/Views and Controls/View.swift
This adds the `View.AnimationOptions` `OptionSet` which is required for
completing the definition of `ViewController.`
> Views and Controls: define `View.AnimationOptions`

- Sources/SwiftWin32/App and Environment/TraitCollection.swift
- Sources/SwiftWin32/CMakeLists.txt
- Sources/SwiftWin32/View Controllers/ViewController.swift
`ViewController` provides a trait environment.  Add a protocol
conformance for this.
> View Controllers: make `ViewController` conform to `TraitEnvironment`

- Examples/Calculator/Calculator.swift
Update the state after mutation to ensure that subsequent mutations will
see the new state.  This allows multi-digit entries again.
> Calculator: repair the calculator

- Sources/SwiftWin32/Views and Controls/View.swift
Correct an incorrect quote character that was inserted in a comment to
match the rest of the project.
> View: replace unnecessary unicode to be more consistent (NFC)

- Sources/SwiftWin32/App and Environment/TraitCollection.swift
Improve the documentation coverage for TraitCollection types.  Change
some of the values for enumerated types.
> App and Environment: tweak TraitCollection types

- Sources/SwiftWin32/Drag and Drop/SpringLoadedInteractionContext.swift
Correct indentation for enumeration.
> Drag and Drop: correct style (NFC)

- .github/workflows/build.yml
> CI: add a 5.6 build

- .github/workflows/build.yml
This adds a 5.7 build stream for testing.
> CI: add 5.7 build stream

- Sources/SwiftWin32/App and Environment/ApplicationMain.swift
Rather than creating a timer to wait for a message for a predefined
period, use `MsgWaitForMultipleObjects` to avoid race conditions.  It
also avoids unnecessarily creating new handles on each poll.  This
allows us to poll more effectively for any messages.
> SwiftWin32: remove custom `WaitMessage` wrapper

- .github/workflows/build.yml
Update to a more recent 5.7 snapshot.
> Update 5.7 release train snapshot

- .github/workflows/build.yml
Update the development train to the latest toolchain.
> GHA: update dev train to latest snapshot

- Sources/SwiftWin32/View Controllers/ViewController.swift
Add some missing interfaces and mark the class as `open`.
> View Controllers: mark `ViewController` interfaces open

- Package.swift
Reflow some text to make the definition more compact.
> build: reflow text in `Package.swift`

- Package.swift
Reflow the text to be easier to read. This matches the rest of the project style.
> build: reflow some text for `Package.swift`
